/* ═══════════════════════════════════════════════════════════════════════
   LONDON AI ECOSYSTEM — DATA
   Companies · Edges · People w/ podcasts · Updates w/ news links
   ═══════════════════════════════════════════════════════════════════════ */

export const CC={
  frontier:{c:"#FF2D55",l:"Frontier Labs",i:"⚡"},
  "frontier-emerging":{c:"#FF6B9D",l:"Emerging Frontier",i:"🌟"},
  autonomous:{c:"#00D4FF",l:"Autonomous",i:"🚗"},
  generative:{c:"#BF5AF2",l:"Generative AI",i:"🎨"},
  biotech:{c:"#30D158",l:"AI + Biotech",i:"🧬"},
  enterprise:{c:"#FFD60A",l:"Enterprise AI",i:"🏢"},
  hardware:{c:"#5E5CE6",l:"AI Hardware",i:"🔧"},
  fintech:{c:"#64D2FF",l:"AI Fintech",i:"💰"},
  defence:{c:"#FF375F",l:"Security / Defence",i:"🛡️"},
  safety:{c:"#FF9F0A",l:"AI Safety",i:"🔒"},
  devtools:{c:"#32D74B",l:"Dev Tools",i:"⚙️"},
  investor:{c:"#FFD700",l:"Investors",i:"💎"},
  academic:{c:"#5AC8FA",l:"Academic",i:"🎓"},
};

export const ECfg={
  alumni:{c:"#FF2D55",l:"Alumni Flow"},
  spinoff:{c:"#BF5AF2",l:"Spin-off"},
  investment:{c:"#FFD700",l:"Investment"},
  academic:{c:"#5AC8FA",l:"Academic"},
  partnership:{c:"#64D2FF",l:"Partnership",d:"6,3"},
  accelerator:{c:"#FF9500",l:"Accelerator"},
};

export const US={
  know_someone:{c:"#30D158",l:"Know Someone",i:"🤝",pts:15},
  applied:{c:"#FFD60A",l:"Applied",i:"📨",pts:5},
  target:{c:"#00D4FF",l:"Target",i:"🎯",pts:3},
  interviewing:{c:"#BF5AF2",l:"Interviewing",i:"💬",pts:20},
  rejected:{c:"#FF453A",l:"Rejected",i:"❌",pts:2},
  watching:{c:"#64748B",l:"Watching",i:"👁️",pts:1},
};

export const BADGES=[
  {id:"frontier_tracker",name:"Frontier Tracker",desc:"Track all 7 frontier labs",icon:"⚡",check:ud=>["deepmind","anthropic","openai","meta-ai","ms-research","mistral","cohere"].filter(id=>ud[id]).length>=7},
  {id:"dm_insider",name:"DeepMind Insider",desc:"3+ DeepMind-linked companies",icon:"🧠",check:(ud)=>{const dm=edges.filter(e=>e.s==="deepmind"||e.t==="deepmind").flatMap(e=>[e.s,e.t]);return Object.keys(ud).filter(id=>dm.includes(id)).length>=3;}},
  {id:"seed_scout",name:"Seed Scout",desc:"Track 10+ emerging startups",icon:"🌱",check:(ud)=>Object.keys(ud).filter(id=>{const co=companies.find(c=>c.id===id);return co&&co.fn<100&&co.fn>0;}).length>=10},
  {id:"money_trail",name:"Money Trail",desc:"Track 5+ investors",icon:"💎",check:(ud)=>Object.keys(ud).filter(id=>{const co=companies.find(c=>c.id===id);return co?.cat==="investor";}).length>=5},
  {id:"first_contact",name:"First Contact",desc:"Add your first connection",icon:"👋",check:ud=>Object.keys(ud).length>=1},
  {id:"networker",name:"Networker",desc:"Track 15+ companies",icon:"🕸️",check:ud=>Object.keys(ud).length>=15},
  {id:"power_player",name:"Power Player",desc:"Track 30+ companies",icon:"👑",check:ud=>Object.keys(ud).length>=30},
  {id:"unicorn_hunter",name:"Unicorn Hunter",desc:"5+ unicorns ($1B+)",icon:"🦄",check:(ud)=>Object.keys(ud).filter(id=>{const co=companies.find(c=>c.id===id);return co&&co.fn>=500;}).length>=5},
];

// ── PEOPLE WITH PODCASTS ────────────────────────────────────────────────
export const PEOPLE={
  "Demis Hassabis":{role:"CEO, Google DeepMind & Isomorphic Labs",tw:"https://x.com/demishassabis",li:"https://linkedin.com/in/demishassabis/",co:["deepmind","isomorphic"],pods:[
    {label:"DeepMind Podcast S3 w/ Hannah Fry — Gemini 3, world models, AGI, curing diseases (2026)",url:"https://youtu.be/PqVbypvxDto"},
    {label:"Lex Fridman #475 — Future of AI (2025)",url:"https://lexfridman.com/demis-hassabis-2/"},
    {label:"CBS 60 Minutes (Apr 2025)",url:"https://www.cbsnews.com/video/demis-hassabis-ai-deepmind-60-minutes-video-2025-04-20/"},
    {label:"Nobel Chemistry 2024 — Official lecture",url:"https://www.nobelprize.org/prizes/chemistry/2024/hassabis/interview/"},
    {label:"Lex Fridman #299 — Superintelligence",url:"https://lexfridman.com/demis-hassabis/"},
    {label:"BBC Desert Island Discs (2017)",url:"https://www.bbc.co.uk/programmes/b08qy1sl"},
  ]},
  "Dario Amodei":{role:"CEO, Anthropic",tw:"https://x.com/DarioAmodei",li:"https://linkedin.com/in/dario-amodei-3934934/",co:["anthropic"],pods:[
    {label:"Dwarkesh Patel — Near end of exponential (Feb 2026)",url:"https://www.dwarkesh.com/p/dario-amodei-2"},
    {label:"Lex Fridman #452 — Claude, AGI (5h, Nov 2024)",url:"https://www.youtube.com/watch?v=ugvHCXCOmm4"},
    {label:"Dwarkesh Patel — $10B Models (Aug 2023)",url:"https://www.dwarkesh.com/p/dario-amodei"},
    {label:"In Good Company w/ Nicolai Tangen (Jan 2025)",url:"https://open.spotify.com/episode/6UzOVEv3Upt5oHAMZw9Gzx"},
  ]},
  "Sam Altman":{role:"CEO, OpenAI",tw:"https://x.com/sama",li:"https://linkedin.com/in/samaltman/",co:["openai"],pods:[
    {label:"TED 2025 — AI Agents & Superintelligence (Apr 2025)",url:"https://www.ted.com/talks/sam_altman_openai_s_sam_altman_talks_chatgpt_ai_agents_and_superintelligence_live_at_ted2025"},
    {label:"Conversations with Tyler (Oct 2025)",url:"https://conversationswithtyler.com/episodes/sam-altman-2/"},
    {label:"Lex Fridman #419 — GPT-5, Sora, Board (Mar 2024)",url:"https://lexfridman.com/sam-altman-2/"},
    {label:"All-In Podcast — In Conversation (May 2024)",url:"https://open.spotify.com/episode/0rka7b2zunmx6f0etLWRGB"},
    {label:"Joe Rogan #2044 (Oct 2023)",url:"https://open.spotify.com/episode/66edV3LAbUXa26HG1ZQaKB"},
  ]},
  "Arthur Mensch":{role:"CEO, Mistral AI",tw:"https://x.com/arthurmensch",li:"https://linkedin.com/in/arthur-mensch/",co:["mistral"],pods:[
    {label:"CNBC India AI Summit (Feb 2026)",url:"https://www.cnbc.com/video/2026/02/18/watch-cnbcs-full-interview-with-mistral-ai-ceo-arthur-mensch.html"},
    {label:"CNBC Squawk Box (Sep 2025)",url:"https://www.cnbc.com/video/2025/09/09/watch-cnbcs-full-interview-with-mistral-ai-founder-and-ceo-arthur-mensch.html"},
    {label:"No Priors #40 — Open Source Revolution",url:"https://open.spotify.com/episode/2H7gV2CgfzS7jXK4Mx8v9j"},
    {label:"TIME Magazine interview",url:"https://time.com/7007040/mistral-ai-ceo-arthur-mensch-interview/"},
  ]},
  "Aidan Gomez":{role:"CEO, Cohere",tw:"https://x.com/aidangomez",li:"https://linkedin.com/in/aidangomez/",co:["cohere"],pods:[
    {label:"No Priors #91 — Model Plateaus (Oct 2024)",url:"https://open.spotify.com/episode/4ALfoL5D1bujniynuy76yM"},
    {label:"MAD Podcast — Paper That Changed AI (Feb 2025)",url:"https://open.spotify.com/episode/70RgbeBY38bhP4wSshSEGW"},
    {label:"MLST — AI's Inner Monologue (Jun 2024)",url:"https://open.spotify.com/episode/0oFwBJG0lBdbBaHK1M8L8H"},
  ]},
  "Alex Kendall":{role:"CEO, Wayve",tw:"https://x.com/alexgkendall",li:"https://linkedin.com/in/alexgkendall/",co:["wayve"],pods:[
    {label:"Sequoia Training Data — AV 2.0 (Nov 2025)",url:"https://sequoiacap.com/podcast/how-end-to-end-learning-created-autonomous-driving-2-0-wayve-ceo-alex-kendall/"},
    {label:"Sifted — Vindicated by Elon Musk (2023)",url:"https://sifted.eu/articles/wayves-alex-kendall-sifted-podcast"},
    {label:"TechCrunch — Autonomous Future (May 2024)",url:"https://techcrunch.com/2024/05/07/exclusive-wayve-cofounder-alex-kendall-on-the-autonomous-future-for-cars-and-robots/"},
  ]},
  "Victor Riparbelli":{role:"CEO, Synthesia",tw:"https://x.com/vriparbelli",li:"https://linkedin.com/in/victorriparbelli/",co:["synthesia"],pods:[
    {label:"CNBC Executive Decisions (Jan 2026)",url:"https://www.cnbc.com/video/2026/01/13/synthesia-ceo-victor-riparbelli-executive-decisions-with-steve-sedgwick.html"},
    {label:"20VC E1246 — OpenAI vs Anthropic (Sep 2024)",url:"https://open.spotify.com/episode/4Qe1XP4sPOLBZ8tAA4P0Er"},
    {label:"TWIST — $1B AI Avatar Business (Jan 2025)",url:"https://thisweekinstartups.com/episodes/EbY2M03ANMs"},
    {label:"Accel Spotlight On (2024)",url:"https://www.accel.com/podcast-episodes/synthesia-victor-riparbelli"},
  ]},
  "Mati Staniszewski":{role:"CEO, ElevenLabs",tw:"https://x.com/matistanis",li:"https://linkedin.com/in/matiii/",co:["elevenlabs"],pods:[
    {label:"Sequoia — Scaling AI Rocketships (Nov 2025)",url:"https://sequoiacap.com/podcast/scaling-ai-rocketships-elevenlabs-mati-staniszewski-lovables-anton-osika/"},
    {label:"20VC — $200M ARR Untold Story (Sep 2025)",url:"https://open.spotify.com/episode/12pXbRQVhbx91MyBydH64i"},
    {label:"Bloomberg TV — $330M ARR (Jan 2026)",url:"https://www.bloomberg.com/news/videos/2026-01-12/elevenlabs-330m-crossed-in-arr-video"},
  ]},
  "Connor Leahy":{role:"CEO, Conjecture",tw:"https://x.com/NPCollapse",li:"https://linkedin.com/in/connor-j-leahy/",co:["conjecture"],pods:[
    {label:"FLI — Extinction Risk from AGI (Jul 2023)",url:"https://futureoflife.org/podcast/connor-leahy-on-why-humanity-risks-extinction-from-agi/"},
    {label:"MLST — e/acc vs Doomer Showdown (Dec 2023)",url:"https://www.youtube.com/watch?v=0zxi0xSBOaQ"},
    {label:"FLI — AGI & Cognitive Emulation (May 2023)",url:"https://futureoflife.org/podcast/connor-leahy-on-agi-and-cognitive-emulation/"},
  ]},
  "Yann LeCun":{role:"AMI Labs (ex-Meta FAIR Chief)",tw:"https://x.com/ylecun",li:"https://linkedin.com/in/yann-lecun-0b999/",co:["meta-ai"],pods:[
    {label:"Lex Fridman #416 — Limits of LLMs (Mar 2024)",url:"https://lexfridman.com/yann-lecun-3/"},
    {label:"TED — Future of AI (2021)",url:"https://www.ted.com/talks/yann_lecun_deep_learning_neural_networks_and_the_future_of_ai"},
    {label:"Lex Fridman #258 — Dark Matter (Feb 2022)",url:"https://lexfridman.com/yann-lecun-2/"},
  ]},
  "Mustafa Suleyman":{role:"CEO Microsoft AI, DeepMind co-founder",tw:"https://x.com/mustafasuleyman",li:"https://linkedin.com/in/mustafa-suleyman/",co:["ms-research","deepmind"],pods:[
    {label:"Bloomberg — AI Is Already Superhuman (Dec 2025)",url:"https://www.bloomberg.com/features/2025-mustafa-suleyman-weekend-interview/"},
    {label:"TED 2024 — What is an AI Anyway?",url:"https://www.youtube.com/watch?v=KKNCiRWd_j0"},
    {label:"CNBC — Full interview (Apr 2025)",url:"https://www.cnbc.com/video/2025/04/04/watch-cnbcs-full-interview-with-microsoft-ai-ceo-mustafa-suleyman.html"},
  ]},
  "David Silver":{role:"Founder, Ineffable Intelligence",tw:null,li:null,co:["ineffable","deepmind"],pods:[
    {label:"Lex Fridman #86 — AlphaGo, AlphaZero",url:"https://www.youtube.com/watch?v=uPUEq8d73JI"},
    {label:"UCL RL Course — Lecture 1 (legendary)",url:"https://www.youtube.com/watch?v=2pWv7GOvuf0"},
    {label:"TalkRL — RLC 2024",url:"https://www.talkrl.com/episodes/david-silver-rcl-2024/transcript"},
  ]},
  "Nathan Benaich":{role:"GP, Air Street Capital",tw:"https://x.com/nathanbenaich",li:"https://linkedin.com/in/nathanbenaich/",co:["air-street"],pods:[
    {label:"Hidden Forces #448 — State of AI 2025",url:"https://hiddenforces.io/podcasts/investing-on-the-front-lines-of-the-ai-arms-race-nathan-benaich/"},
    {label:"State of AI 2025 — Launch video + report",url:"https://www.stateof.ai/2025-report-launch"},
    {label:"The PEEL — 2-hour deep dive (Nov 2024)",url:"https://www.thespl.it/p/the-state-of-ai-with-nathan-benaich"},
  ]},
  "Ian Hogarth":{role:"AISI Chair, Plural co-founder",tw:"https://x.com/soundboy",li:"https://linkedin.com/in/ianhogarth/",co:["plural"],pods:[
    {label:"AI Breakdown — Head of UK AI Taskforce (Jun 2023)",url:"https://podcasts.apple.com/us/podcast/what-the-head-of-the-new-uk-ai-foundation/id1680633614?i=1000618244541"},
    {label:"Sifted — ML will eat the world (2019)",url:"https://sifted.eu/articles/ian-hogarth-machine-learning-will-eat-the-world"},
    {label:"TIME 100 AI profile (Sep 2023)",url:"https://time.com/collection/time100-ai/6309473/ian-hogarth/"},
  ]},
  "Poppy Gustafsson":{role:"Baroness, ex-Darktrace CEO, UK Min. for Investment",tw:"https://x.com/PoppyGustafsson",li:"https://linkedin.com/in/poppy-gustafsson-41464ba0/",co:["darktrace"],pods:[
    {label:"BoS Europe — Scaling AI at Warp Speed (2019)",url:"https://businessofsoftware.org/talks/billion-dollar-business/"},
    {label:"csuite Podcast — Unicorn CEOs (2021)",url:"https://www.csuitepodcast.com/show-92-unicorn-ceos-poppy-gustafsson-obe-ceo-of-darktrace/"},
    {label:"TIME — Fighting Cyber Attacks (May 2021)",url:"https://time.com/6048319/poppy-gustafsson-darktrace-cyber-attacks/"},
  ]},
  "Nikola Mrkšić":{role:"CEO, PolyAI",tw:"https://x.com/nikola_mrksic",li:"https://linkedin.com/in/nikola-mrksic/",co:["polyai"],pods:[
    {label:"Practical AI — Next-Gen Voice (2024)",url:"https://poly.ai/blog/nikola-mrksic-on-the-practical-ai-podcast/"},
    {label:"tech.eu — Our future is American (Feb 2025)",url:"https://tech.eu/2025/02/19/our-future-is-predominantly-american-says-founder-of-nvidia-backed-london-startup-polyai/"},
    {label:"Unite.AI — Interview Series (2023)",url:"https://www.unite.ai/nikola-mrksic-co-founder-and-ceo-of-polyai-interview-series/"},
  ]},
  "Guy Podjarny":{role:"CEO, Tessl (ex-Snyk $7.4B)",tw:"https://x.com/guypod",li:"https://linkedin.com/in/guypo/",co:["tessl"],pods:[
    {label:"Scaling DevTools — Future of Programming (2025)",url:"https://scalingdevtools.com/podcast/episodes/guy-podjarny"},
    {label:"PMF Show — $4M to $4.5M ARR (2024)",url:"https://www.pmf.show/guy-podjarny-snyk-product-buyer-fit-growth/"},
    {label:"Changelog Founders Talk #71 (2019)",url:"https://changelog.com/founderstalk/71"},
  ]},
  "Torsten Reil":{role:"Co-CEO, Helsing",tw:"https://x.com/torstenreil",li:"https://linkedin.com/in/torstenreil/",co:["helsing"],pods:[
    {label:"Bloomberg — AI in Defence (Oct 2025)",url:"https://www.bloomberg.com/news/videos/2025-10-21/helsing-s-reil-on-ai-s-role-in-defense-innovation-video"},
    {label:"20VC — Raising $828M for Defence (Jun 2025)",url:"https://www.thetwentyminutevc.com/torsten-reil"},
    {label:"FT Lunch — AI Drones & VC Herd (Mar 2025)",url:"https://www.techmeme.com/250323/p11"},
  ]},
  "Barney Hussey-Yeo":{role:"CEO, Cleo AI",tw:"https://x.com/Barney_H_Y",li:"https://linkedin.com/in/bhusseyyeo/",co:["cleo"],pods:[
    {label:"Sifted — Build £100bn & Save Democracy (2024)",url:"https://sifted.eu/articles/cleo-big-interview"},
    {label:"Jimmy's Jobs — UK Unicorns (Nov 2024)",url:"https://open.spotify.com/episode/4kX02ccyFWYXgsFmEa1nOA"},
    {label:"11:FS — AI for Financial Wellbeing (2023)",url:"https://content.11fs.com/videos/harnessing-the-power-of-ai-to-improve-financial-wellbeing"},
  ]},
  "Alex Dalyac":{role:"CEO, Tractable",tw:"https://x.com/alexdalyac",li:"https://linkedin.com/in/adalyac/",co:["tractable"],pods:[
    {label:"EF Podcast — Billion Dollar Story (w/ Reid Hoffman)",url:"https://podcasts.apple.com/gb/podcast/the-billion-dollar-story-of-tractable/id1581333327?i=1000533165537"},
    {label:"World of DaaS — Building a CV Unicorn (Feb 2022)",url:"https://podcasts.apple.com/us/podcast/alex-dalyac-the-secret-to-building-a-computer/id1570644971?i=1000551139486"},
    {label:"EF — From EF to $1B Story (2021)",url:"https://www.joinef.com/stories/the-story-of-tractable/"},
  ]},
  // Additional key people — co-founders, CPOs, CTOs
  "Daniela Amodei":{role:"President & Co-founder, Anthropic",tw:null,li:"https://linkedin.com/in/daniela-amodei/",co:["anthropic"],pods:[]},
  "Tom Brown":{role:"Co-founder & CEO, Sakana AI (ex-OpenAI, GPT-3 lead)",tw:"https://x.com/tombbrown",li:null,co:["openai"],pods:[]},
  "John Jumper":{role:"Senior Director, Google DeepMind (Nobel Prize 2024, AlphaFold)",tw:null,li:null,co:["deepmind","isomorphic"],pods:[]},
  "Lila Ibrahim":{role:"COO, Google DeepMind",tw:"https://x.com/lilaibrahim",li:"https://linkedin.com/in/lilaibrahim/",co:["deepmind"],pods:[]},
  "Matt Clifford":{role:"Co-founder, EF · UK AI Advisor to PM",tw:"https://x.com/matthewclifford",li:"https://linkedin.com/in/mattclifford/",co:["ef"],pods:[]},
  "James Wise":{role:"Partner, Balderton · Chair, UK Sovereign AI",tw:"https://x.com/jameswisevc",li:"https://linkedin.com/in/jamesjwise/",co:["balderton","sovereign-ai"],pods:[]},
  "Sid Jayakumar":{role:"CEO & Founder, Finster AI (ex-DeepMind 7yr)",tw:null,li:null,co:["finster"],pods:[]},
  "Steve Basher":{role:"CEO & Founder, SolveAI (ex-Palantir 8yr)",tw:null,li:null,co:["solveai"],pods:[]},
  "Joelle Pineau":{role:"Chief AI Officer, Cohere (ex-Meta FAIR VP)",tw:"https://x.com/jpineau_",li:null,co:["cohere"],pods:[]},
  "Azeem Azhar":{role:"Founder, Exponential View · AI analyst",tw:"https://x.com/azaboreal",li:"https://linkedin.com/in/azeem/",co:[],pods:[]},
  "Danyal Akarca":{role:"Co-founder & CEO, Callosum (Cambridge neuroscience PhD, Schmidt Fellow)",tw:"https://x.com/DanAkarca",li:null,co:["callosum"],pods:[]},
  "Tim Cherkasov":{role:"Co-founder & CEO, Trace (YC S25, ex-Copper)",tw:"https://x.com/timcherkasov",li:"https://linkedin.com/in/timcherkasov/",co:["trace"],pods:[]},
  "Artur Romanov":{role:"Co-founder & CTO, Trace (YC S25, ex-Deliveroo)",tw:null,li:"https://linkedin.com/in/artur-romanov/",co:["trace"],pods:[]},
  "Arjun Khanna":{role:"Co-founder & CPO, Mozart AI",tw:"https://x.com/arjunskhanna19",li:null,co:["mozart-ai"],pods:[]},
  "Hannah Fry":{role:"Professor of Maths (UCL) · Host, Google DeepMind: The Podcast · Broadcaster & Author",tw:"https://x.com/FryRsquared",li:null,co:[],pods:[
    {label:"DeepMind Podcast — Demis Hassabis at AI for Science Forum",url:"https://deepmind.google/the-podcast/"},
    {label:"DeepMind Podcast — David Silver: The Era of Experience",url:"https://deepmind.google/the-podcast/"},
    {label:"DeepMind Podcast — Genie 3: Interactive World Models",url:"https://deepmind.google/the-podcast/"},
    {label:"DeepMind Podcast — Drug Discovery w/ Isomorphic Labs",url:"https://deepmind.google/the-podcast/"},
    {label:"DeepMind Podcast — AI & Ecology: Forests, Reefs, Animal Communication",url:"https://deepmind.google/the-podcast/"},
    {label:"DeepMind Podcast — Murray Shanahan on Consciousness & AI",url:"https://deepmind.google/the-podcast/"},
    {label:"DeepMind Podcast — Cybersecurity: Operation Aurora & AI Defence",url:"https://deepmind.google/the-podcast/"},
    {label:"DeepMind Podcast — NotebookLM: AI Podcasts from Your Documents",url:"https://deepmind.google/the-podcast/"},
    {label:"DeepMind Podcast — Vibe Coding & AI Tools",url:"https://deepmind.google/the-podcast/"},
    {label:"DeepMind Podcast — Levels of AGI: What It Means & When",url:"https://deepmind.google/the-podcast/"},
  ]},
  // ── INVESTOR PEOPLE ──
  "Nathan Benaich":{role:"Founder & GP, Air Street Capital · State of AI Report",tw:"https://x.com/nathanbenaich",li:"https://linkedin.com/in/nathanbenaich/",co:["air-street"],pods:[
    {label:"20VC — State of AI 2025",url:"https://www.youtube.com/watch?v=IxMp4QBQLYE"},
  ]},
  "Suranga Chandratillake":{role:"GP, Balderton Capital · founder Blinkx",tw:"https://x.com/surangac",li:"https://linkedin.com/in/surangac/",co:["balderton"],pods:[
    {label:"20VC — AI Investing in Europe (2024)",url:"https://www.youtube.com/watch?v=5tlS2Ih3p8k"},
  ]},
  "Niklas Zennström":{role:"Founder & CEO, Atomico · co-founder Skype",tw:"https://x.com/nikilas",li:"https://linkedin.com/in/zennstrom/",co:["atomico"],pods:[]},
  "Siraj Khaliq":{role:"GP, Atomico · AI/climate lead",tw:"https://x.com/siloknern",li:"https://linkedin.com/in/sirajkhaliq/",co:["atomico"],pods:[
    {label:"Sifted — Europe's AI Opportunity (2025)",url:"https://sifted.eu/articles/siraj-khaliq-atomico-ai/"},
  ]},
  "Taavet Hinrikus":{role:"Co-Founder, Plural · founder Wise (TransferWise)",tw:"https://x.com/tfrancischanel",li:"https://linkedin.com/in/taavethinrikus/",co:["plural"],pods:[]},
  "Ian Hogarth":{role:"Co-Founder, Plural · Chair, UK AI Safety Institute",tw:"https://x.com/soundboy",li:"https://linkedin.com/in/ianhogarth/",co:["plural"],pods:[
    {label:"Lex Fridman — AI Safety & Regulation (2024)",url:"https://www.youtube.com/watch?v=1yyUFJt6Uuw"},
  ]},
  "Luciana Lixandru":{role:"Partner, Sequoia Capital Europe · ex-Accel",tw:null,li:"https://linkedin.com/in/lixandru/",co:["sequoia-eu","accel"],pods:[]},
  "Tom Hulme":{role:"GP, GV London · founder IDEO/OpenIDEO",tw:"https://x.com/thulme",li:"https://linkedin.com/in/tomhulme/",co:["gv"],pods:[]},
  "Vinod Khosla":{role:"Founder, Khosla Ventures · co-founder Sun Microsystems",tw:"https://x.com/vaboreal",li:"https://linkedin.com/in/vkhosla/",co:["khosla"],pods:[
    {label:"All-In Summit — AI & Energy (2024)",url:"https://www.youtube.com/watch?v=2jN5GKl0qA4"},
  ]},
  "Bernard Liautaud":{role:"Managing Partner, Balderton · founder Business Objects",tw:null,li:"https://linkedin.com/in/bernardliautaud/",co:["balderton"],pods:[]},
  "David Kelnar":{role:"Partner, MMC Ventures · AI Research",tw:"https://x.com/davidkelnar",li:"https://linkedin.com/in/davidkelnar/",co:["mmc"],pods:[]},
  "Saul Klein":{role:"Co-Founder, LocalGlobe · ex-Skype/LoveFilm",tw:"https://x.com/saulklein",li:"https://linkedin.com/in/saulklein/",co:["localglobe"],pods:[]},
  // ── PRINCIPALS & ADDITIONAL VC ──
  "Ameerul Miah":{role:"Principal, MMC Ventures · AI Investments",tw:null,li:"https://linkedin.com/in/ameerul-miah-49089a21/",co:["mmc"],pods:[]},
  "Oliver Richards":{role:"Partner, MMC Ventures",tw:null,li:"https://linkedin.com/in/oliverrichards1/",co:["mmc"],pods:[]},
  "Richard de Vere":{role:"Principal, MMC Ventures",tw:null,li:"https://linkedin.com/in/richard-de-vere-5659a592/",co:["mmc"],pods:[]},
  "Mina Ferdowsi":{role:"Principal, MMC Ventures",tw:null,li:"https://linkedin.com/in/minaferdowsi/",co:["mmc"],pods:[]},
  "Sia Houchangnia":{role:"Principal, Seedcamp · AI/Deep Tech",tw:null,li:"https://linkedin.com/in/siahouchangnia/",co:["seedcamp"],pods:[]},
  "Will Bennett":{role:"Investor, Seedcamp · AI/Crypto",tw:null,li:"https://linkedin.com/in/will-bennett-seedcamp/",co:["seedcamp"],pods:[]},
  "Reshma Sohoni":{role:"Managing Partner, Seedcamp",tw:"https://x.com/reshmasohoni",li:"https://linkedin.com/in/reshmasohoni/",co:["seedcamp"],pods:[]},
  "Carlos Espinal":{role:"Managing Partner, Seedcamp",tw:"https://x.com/cee",li:"https://linkedin.com/in/carlosespinal/",co:["seedcamp"],pods:[]},
  "Robin Klein":{role:"Co-Founder & GP, LocalGlobe",tw:null,li:"https://linkedin.com/in/robinklein/",co:["localglobe"],pods:[]},
  "George Henry":{role:"GP, LocalGlobe",tw:null,li:"https://linkedin.com/in/george-henry-localglobe/",co:["localglobe"],pods:[]},
  "Julia Hawkins":{role:"GP, LocalGlobe",tw:null,li:"https://linkedin.com/in/julia-hawkins-localglobe/",co:["localglobe"],pods:[]},
  "Remus Brett":{role:"GP, LocalGlobe",tw:null,li:"https://linkedin.com/in/remusbrett/",co:["localglobe"],pods:[]},
  "Suzanne Ashman":{role:"GP, LocalGlobe",tw:null,li:"https://linkedin.com/in/suzanneashman/",co:["localglobe"],pods:[]},
  "Sophia Bendz":{role:"GP, Atomico · Consumer/AI",tw:"https://x.com/sophiabendz",li:"https://linkedin.com/in/sophiabendz/",co:["atomico"],pods:[]},
  "Luca Bocchio":{role:"Partner, Accel · AI/Infra",tw:"https://x.com/lucabocchio",li:"https://linkedin.com/in/lucabocchio/",co:["accel"],pods:[]},
  "Harry Sherrill":{role:"Principal, Accel · London",tw:null,li:"https://linkedin.com/in/harrysherrill/",co:["accel"],pods:[]},
  "Martin Mignot":{role:"Partner, Index Ventures · AI",tw:"https://x.com/martinmignot",li:"https://linkedin.com/in/martinmignot/",co:["index"],pods:[]},
  "Tom Sheridan":{role:"Principal, GV London",tw:null,li:"https://linkedin.com/in/tomsheridan/",co:["gv"],pods:[]},
  "Matt Clifford":{role:"Co-founder, EF · UK AI Advisor to PM",tw:"https://x.com/matthewclifford",li:"https://linkedin.com/in/mattclifford/",co:["ef"],pods:[
    {label:"20VC — EF, UK AI Policy (2025)",url:"https://www.youtube.com/watch?v=fqAW43G8zHA"},
  ]},
};

// ── UPDATES WITH NEWS LINKS ─────────────────────────────────────────────
export const UPDATES=[
  {date:"2026-03-09",type:"funding",text:"Nscale raises $2B Series C at $14.6B — largest in European history. Led by Aker ASA & 8090 Industries. Investors: Citadel, Dell, Jane Street, Lenovo, Nokia, NVIDIA, Point72. Sheryl Sandberg, Nick Clegg join board",company:"nscale",link:"https://www.nscale.com/press-releases/nscale-series-c"},
  {date:"2026-03-04",type:"funding",text:"Mutable Tactics raises $2M pre-seed led by Seraphim Space — AI-powered autonomous mission systems for UAVs",company:"mutable-tactics",link:"https://www.londontechwatch.com/2026/03/the-london-techwatch-startup-daily-funding-report-4-3-2026/"},
  {date:"2026-02-01",type:"funding",text:"OLIX raises $220M Series A for optical AI accelerators — light-based photonic processors for training & inference. Backed by Octopus, LocalGlobe, EF, Vertex, Crane, Plural",company:"olix",link:"https://www.londontechwatch.com/2026/03/london-startup-funding-top-largest-february-2026-vc/"},
  {date:"2026-03-04",type:"funding",text:"Vivox AI raises £1.3M for agentic AML/KYB compliance platform — angels include Axel Weber (ex-Bundesbank) and Dan Cobley (ex-Google UK)",company:"vivox-ai",link:"https://www.londontechwatch.com/2026/03/the-london-techwatch-startup-daily-funding-report-4-3-2026/"},
  {date:"2026-03-06",type:"funding",text:"Isembard raises $50M Series A for AI-powered factories — led by Union Square Ventures. MasonOS agentic factory OS, 25 factories planned by end 2026, aerospace & defence",company:"isembard",link:"https://www.isembard.com/blogs-and-articles/isembard-raises-50m-series-a-to-open-25-ai-powered-factories-serving-aerospace-and-defence"},
  {date:"2026-02-26",type:"funding",text:"Callosum raises $10.25M seed led by Plural (Hogarth, Hinrikus) + ARIA gov funding — Cambridge neuroscientists building multi-chip AI orchestration to challenge NVIDIA monoculture",company:"callosum",link:"https://fortune.com/2026/02/26/startup-callosum-cambridge-trained-neuroscientists-raises-10-million-venture-funding-orchestrate-ai-workloads-different-chips/"},
  {date:"2026-02-26",type:"funding",text:"Trace raises $3M seed from YC, Zeno Ventures, Goodwater — London startup building AI agent workflow orchestration for enterprise",company:"trace",link:"https://techcrunch.com/2026/02/26/trace-raises-3-million-to-solve-the-agent-adoption-problem/"},
  {date:"2026-02-11",type:"funding",text:"Mozart AI raises $6M seed led by Balderton Capital — AI Generative Audio Workstation with 100K+ users, 1M songs created, 10M+ Spotify streams",company:"mozart-ai",link:"https://www.balderton.com/news/mozart-ai-scores-6m-from-balderton-to-put-artists-at-the-centre-of-ai-powered-music-making/"},
  {date:"2026-02-25",type:"funding",text:"SolveAI emerges from stealth with $50M — $45M Series A (GV) + $5M pre-seed (Accel). Ex-Palantir founder, 7 months old",company:"solveai",link:"https://fortune.com/2026/02/25/exclusive-solveai-eight-months-raises-50-million-ai-coding-tool-race/"},
  {date:"2026-02-21",type:"milestone",text:"UK Sovereign AI Unit announces £500M fund for British AI startups and sovereign compute — chaired by James Wise (Balderton), launches Apr 16",company:null,link:"https://sovereignai.gov.uk/"},
  {date:"2026-03-01",type:"funding",text:"Wayve closes $1.2B Series D at $8.6B valuation",company:"wayve",link:"https://wayve.ai/thinking/series-d/"},
  {date:"2026-02-04",type:"funding",text:"ElevenLabs raises $500M Series D at $11B, eyes IPO",company:"elevenlabs",link:"https://elevenlabs.io/blog/series-d"},
  {date:"2026-02-01",type:"funding",text:"Encord raises €50M Series C for AI data platform",company:"encord",link:"https://encord.com/blog/series-c/"},
  {date:"2026-01-26",type:"funding",text:"Synthesia raises $200M Series E at $4B from GV & Nvidia",company:"synthesia",link:"https://www.synthesia.io/post/series-e"},
  {date:"2026-01-15",type:"acquisition",text:"Accenture acquires Faculty AI for ~$1B+",company:"faculty",link:"https://newsroom.accenture.com/news/2026/accenture-to-acquire-faculty"},
  {date:"2025-12-15",type:"funding",text:"PolyAI raises $86M Series D (Georgian, Nvidia, Khosla)",company:"polyai",link:"https://poly.ai/blog/series-d/"},
  {date:"2025-11-25",type:"founding",text:"David Silver founds Ineffable Intelligence, seeks $1B seed",company:"ineffable",link:"https://sifted.eu/articles/ineffable-intelligence-david-silver/"},
  {date:"2025-10-20",type:"funding",text:"Finster AI raises $15M Series A + Seed — AI-native financial intelligence for investment banks. Ex-DeepMind founder, FinTech Collective & Peak XV led",company:"finster",link:"https://finster.ai/resources/news/finster-ai-raises-15-million-to-redefine-the-future-of-financial-intelligence"},
  {date:"2025-09-24",type:"funding",text:"Signal AI raises $165M from Battery Ventures",company:"signal-ai",link:"https://www.signal-ai.com/blog/series-e"},
  {date:"2025-09-01",type:"funding",text:"Mimica raises $26.2M Series B, Khosla Ventures",company:"mimica",link:null},
  {date:"2025-08-01",type:"people",text:"Joelle Pineau (ex-Meta FAIR VP) joins Cohere as Chief AI Officer",company:"cohere",link:"https://cohere.com/blog/joelle-pineau-joins-cohere"},
  {date:"2025-07-22",type:"milestone",text:"Latent Labs (DeepMind alumni) launches first AI protein model",company:"latent-labs",link:null},
  {date:"2025-07-01",type:"partnership",text:"OpenAI signs strategic MoU with UK government",company:"openai",link:"https://openai.com/index/openai-and-uk-government/"},
  {date:"2025-06-25",type:"funding",text:"Helsing raises €600M Series D at €12B valuation",company:"helsing",link:"https://helsing.ai/newsroom/series-d"},
  {date:"2025-06-15",type:"funding",text:"PhysicsX raises $135M Series B led by Atomico",company:"physicsx",link:null},
  {date:"2025-06-01",type:"acquisition",text:"Salesforce acquires Convergence AI — 9 months from founding",company:"convergence",link:null},
  {date:"2025-05-01",type:"milestone",text:"Helsing achieves first AI-piloted fighter jet combat",company:"helsing",link:null},
  {date:"2025-04-01",type:"funding",text:"Isomorphic Labs raises $600M Series A from Thrive Capital",company:"isomorphic",link:null},
  {date:"2025-03-24",type:"people",text:"Emad Mostaque resigns as Stability AI CEO",company:"stability",link:"https://stability.ai/news/stabilityai-ceo-transition"},
  {date:"2022-08-22",type:"milestone",text:"Stability AI launches Stable Diffusion — open image gen revolution",company:"stability",link:null},
  // 2024
  {date:"2024-11-01",type:"acquisition",text:"Recursion Pharmaceuticals acquires Exscientia for $688M",company:"exscientia",link:null},
  {date:"2024-10-09",type:"milestone",text:"Demis Hassabis & John Jumper win Nobel Prize in Chemistry for AlphaFold",company:"deepmind",link:"https://www.nobelprize.org/prizes/chemistry/2024/hassabis/facts/"},
  {date:"2024-09-01",type:"funding",text:"Synthesia raises $90M Series D at $2.1B valuation",company:"synthesia",link:null},
  {date:"2024-06-01",type:"funding",text:"ElevenLabs raises $80M Series B at $1.1B — becomes unicorn",company:"elevenlabs",link:null},
  {date:"2024-05-07",type:"funding",text:"Wayve raises $1.05B Series C led by SoftBank — UK's largest AI round",company:"wayve",link:"https://wayve.ai/thinking/series-c/"},
  {date:"2024-04-24",type:"milestone",text:"Microsoft opens new AI Hub in Paddington, London — Suleyman's base",company:"ms-research",link:null},
  {date:"2024-04-01",type:"acquisition",text:"Entrust acquires Onfido for $650M",company:"onfido",link:null},
  {date:"2024-03-01",type:"people",text:"Emad Mostaque steps down as Stability AI CEO",company:"stability",link:"https://stability.ai/news/stabilityai-ceo-transition"},
  {date:"2024-02-01",type:"funding",text:"Helsing raises €209M Series B",company:"helsing",link:null},
  {date:"2024-01-22",type:"funding",text:"ElevenLabs raises $80M Series B from Andreessen Horowitz, Nvidia, others",company:"elevenlabs",link:null},
  // 2023
  {date:"2023-11-01",type:"milestone",text:"UK hosts first-ever global AI Safety Summit at Bletchley Park — 28 countries sign Bletchley Declaration",company:null,link:"https://www.aisafetysummit.gov.uk/"},
  {date:"2023-11-02",type:"founding",text:"UK launches AI Safety Institute (AISI) — Ian Hogarth chairs, world's first state-backed AI safety body",company:null,link:"https://www.gov.uk/government/news/uk-launches-ai-safety-institute"},
  {date:"2023-10-01",type:"funding",text:"Mistral AI raises €385M Series A at €2B — 6 months after founding",company:"mistral",link:null},
  {date:"2023-09-01",type:"funding",text:"Stability AI raises $25M convertible note (down from $4B peak valuation)",company:"stability",link:null},
  {date:"2023-06-15",type:"milestone",text:"OpenAI opens London office in King's Cross — first non-US location",company:"openai",link:null},
  {date:"2023-06-01",type:"founding",text:"Mistral AI founded by Arthur Mensch (ex-DeepMind) with €105M seed — Europe's largest seed round",company:"mistral",link:null},
  {date:"2023-05-15",type:"milestone",text:"Anthropic opens London office in Cheapside — first European base",company:"anthropic",link:null},
  {date:"2023-04-20",type:"milestone",text:"Google merges DeepMind and Google Brain into 'Google DeepMind' — Hassabis leads unified unit",company:"deepmind",link:"https://blog.google/technology/ai/april-ai-update/"},
  {date:"2023-03-14",type:"milestone",text:"GPT-4 released — multimodal, massive capability jump from GPT-3.5",company:"openai",link:"https://openai.com/research/gpt-4"},
  {date:"2023-02-01",type:"funding",text:"Helsing raises $223M Series A — European defence AI takes off",company:"helsing",link:null},
  {date:"2023-01-23",type:"funding",text:"ElevenLabs raises $19M seed — AI voice synthesis takes off",company:"elevenlabs",link:null},
  {date:"2023-01-10",type:"funding",text:"Wayve raises $200M Series B led by Microsoft and Virgin Global",company:"wayve",link:null},
  // 2022
  {date:"2022-11-30",type:"milestone",text:"OpenAI launches ChatGPT — reaches 100M users in 2 months, fastest consumer app ever",company:"openai",link:null},
  {date:"2022-10-01",type:"funding",text:"Stability AI raises $101M seed at $1B valuation — bootstrapped to unicorn",company:"stability",link:null},
  {date:"2022-07-01",type:"milestone",text:"AlphaFold predicts structure of nearly every known protein (~200M) — open-sourced",company:"deepmind",link:"https://deepmind.google/discover/blog/alphafold-reveals-the-structure-of-the-protein-universe/"},
  {date:"2022-04-01",type:"funding",text:"Synthesia raises $50M Series B at $1B valuation — AI video unicorn",company:"synthesia",link:null},
  {date:"2022-03-01",type:"founding",text:"Conjecture founded by Connor Leahy — AI safety research startup, $3.6M pre-seed",company:"conjecture",link:null},
  {date:"2022-01-01",type:"funding",text:"Graphcore raises $222M at $2.77B valuation",company:"graphcore",link:null},
  // 2021
  {date:"2021-11-04",type:"milestone",text:"Isomorphic Labs founded by Demis Hassabis as standalone Alphabet company for AI drug discovery",company:"isomorphic",link:null},
  {date:"2021-09-22",type:"milestone",text:"UK publishes National AI Strategy — commits to 10-year plan for AI leadership",company:null,link:"https://www.gov.uk/government/publications/national-ai-strategy"},
  {date:"2021-07-21",type:"funding",text:"Tractable raises $60M Series D at $1B — UK's first computer vision unicorn",company:"tractable",link:null},
  {date:"2021-07-01",type:"milestone",text:"Anthropic founded by Dario & Daniela Amodei and other ex-OpenAI researchers — focus on AI safety",company:"anthropic",link:null},
  {date:"2021-06-01",type:"funding",text:"Graphcore raises $222M Series E, bringing total to $710M",company:"graphcore",link:null},
  {date:"2021-04-30",type:"milestone",text:"Darktrace IPOs on London Stock Exchange at £1.7B valuation",company:"darktrace",link:null},
  {date:"2021-02-01",type:"milestone",text:"BenevolentAI's AI-identified drug baricitinib approved for COVID-19 — discovered by AI in days",company:"benevolentai",link:null},
  {date:"2021-01-01",type:"funding",text:"Wayve raises $20M Series A — end-to-end driving from camera only",company:"wayve",link:null},
  // 2020
  {date:"2020-11-30",type:"milestone",text:"AlphaFold 2 solves protein structure prediction — CASP14 breakthrough, called 'once in a generation advance'",company:"deepmind",link:"https://deepmind.google/discover/blog/alphafold-a-solution-to-a-50-year-old-grand-challenge-in-biology/"},
  {date:"2020-10-01",type:"funding",text:"BenevolentAI raises $115M — AI drug discovery accelerated by COVID success",company:"benevolentai",link:null},
  {date:"2020-09-01",type:"funding",text:"Synthesia raises $3.5M seed — AI avatar video platform launches",company:"synthesia",link:null},
  {date:"2020-07-01",type:"funding",text:"Graphcore raises $150M at $1.95B — Bristol AI chip unicorn",company:"graphcore",link:null},
  {date:"2020-01-01",type:"founding",text:"Abound founded in London — AI lending using Open Banking data",company:"abound",link:null},
  // 2019
  {date:"2019-12-01",type:"funding",text:"Onfido raises $100M Series D — AI identity verification at scale",company:"onfido",link:null},
  {date:"2019-10-01",type:"milestone",text:"DeepMind achieves first AI to reach Grandmaster level in StarCraft II (AlphaStar)",company:"deepmind",link:null},
  {date:"2019-06-01",type:"founding",text:"Air Street Capital founded by Nathan Benaich — first AI-specialist VC fund in London",company:"air-street",link:null},
  {date:"2019-02-01",type:"funding",text:"Graphcore raises $200M Series D from BMW, Microsoft, others at $1.7B",company:"graphcore",link:null},
  // 2018
  {date:"2018-12-06",type:"milestone",text:"DeepMind publishes AlphaFold — wins CASP13, predicting protein structure from sequence alone",company:"deepmind",link:null},
  {date:"2018-12-01",type:"milestone",text:"AlphaZero published in Science — masters chess, shogi, and Go from self-play alone",company:"deepmind",link:null},
  {date:"2018-06-01",type:"funding",text:"Darktrace raises $50M Series E at $1.65B valuation — Cambridge cyber unicorn",company:"darktrace",link:null},
  {date:"2018-03-01",type:"funding",text:"BenevolentAI raises $115M — largest European AI investment at the time",company:"benevolentai",link:null},
  // 2017
  {date:"2017-10-18",type:"milestone",text:"AlphaGo Zero published — masters Go from scratch with zero human knowledge, surpasses all previous versions",company:"deepmind",link:null},
  {date:"2017-05-27",type:"milestone",text:"AlphaGo defeats Ke Jie 3-0 at Future of Go Summit — retires from competitive play",company:"deepmind",link:null},
  {date:"2017-01-01",type:"founding",text:"Wayve founded by Alex Kendall (Cambridge PhD) — end-to-end autonomous driving with AI",company:"wayve",link:null},
  {date:"2017-01-01",type:"founding",text:"Synthesia founded by Victor Riparbelli — AI video generation for enterprise",company:"synthesia",link:null},
  // 2016
  {date:"2016-03-15",type:"milestone",text:"AlphaGo defeats Lee Sedol 4-1 in Seoul — watched by 200M people, decade ahead of predictions",company:"deepmind",link:"https://deepmind.google/research/alphago/"},
  {date:"2016-09-01",type:"funding",text:"Graphcore founded by Nigel Toon and Simon Knowles — AI chip startup, Bristol + London",company:"graphcore",link:null},
  {date:"2016-01-27",type:"milestone",text:"DeepMind's AlphaGo published in Nature — first AI to defeat professional Go player (Fan Hui 5-0)",company:"deepmind",link:"https://www.nature.com/articles/nature16961"},
  // People moves — founders leaving to start new companies
  {date:"2025-11-01",type:"people",text:"David Silver leaves DeepMind after 15 years to found Ineffable Intelligence — seeking $1B seed for RL superintelligence",company:"ineffable",link:"https://sifted.eu/articles/ineffable-intelligence-david-silver/"},
  {date:"2025-01-01",type:"people",text:"Simon Kohl (core AlphaFold2 team) leaves DeepMind to found Latent Labs — AI protein design",company:"latent-labs",link:null},
  {date:"2024-02-01",type:"people",text:"Guy Podjarny (Snyk founder, $7.4B exit) launches Tessl — AI-native spec-driven development, raises $125M pre-product",company:"tessl",link:null},
  {date:"2023-06-01",type:"people",text:"Arthur Mensch leaves DeepMind to co-found Mistral AI — raises €105M seed, Europe's largest ever",company:"mistral",link:null},
  {date:"2021-07-01",type:"people",text:"Dario & Daniela Amodei leave OpenAI to found Anthropic — focus on AI safety research",company:"anthropic",link:null},
  {date:"2021-11-01",type:"people",text:"Demis Hassabis founds Isomorphic Labs as standalone Alphabet company — dual CEO with DeepMind",company:"isomorphic",link:null},
  {date:"2019-03-01",type:"people",text:"Mustafa Suleyman placed on leave from DeepMind, later joins Google as VP AI — eventually becomes Microsoft AI CEO",company:"ms-research",link:null},
  {date:"2025-11-19",type:"people",text:"Yann LeCun leaves Meta to found AMI Labs (Advanced Machine Intelligence) — €500M+ backing reported",company:"meta-ai",link:null},
  {date:"2024-06-01",type:"people",text:"Convergence AI founders (ex-Cohere, ex-DeepMind) acquired by Salesforce — 9 months from founding to exit",company:"convergence",link:null},
  {date:"2022-01-01",type:"people",text:"Connor Leahy (EleutherAI co-founder) launches Conjecture in London — AI safety startup, Karpathy & Collisons invest",company:"conjecture",link:null},
  {date:"2024-01-01",type:"people",text:"Joelle Pineau steps down as Meta FAIR VP Research — later joins Cohere as Chief AI Officer (Aug 2025)",company:"cohere",link:null},
  {date:"2024-01-15",type:"people",text:"Poppy Gustafsson (ex-Darktrace CEO, post Thoma Bravo acquisition) appointed UK Minister for Investment",company:"darktrace",link:null},
  // Interviews / podcasts as updates — generated from all PEOPLE data
  // Demis Hassabis
  {date:"2026-03-01",type:"interview",text:"Demis Hassabis w/ Hannah Fry — DeepMind Podcast S3: Gemini 3, world models, AGI timeline, AI curing most diseases in 10-20 years",company:"deepmind",link:"https://youtu.be/PqVbypvxDto"},
  {date:"2025-11-01",type:"interview",text:"Demis Hassabis on Lex Fridman #475 — Future of AI, post-Nobel",company:"deepmind",link:"https://lexfridman.com/demis-hassabis-2/"},
  {date:"2025-04-20",type:"interview",text:"Demis Hassabis on CBS 60 Minutes with Scott Pelley",company:"deepmind",link:"https://www.cbsnews.com/video/demis-hassabis-ai-deepmind-60-minutes-video-2025-04-20/"},
  {date:"2024-10-10",type:"interview",text:"Demis Hassabis — Nobel Prize in Chemistry official lecture",company:"deepmind",link:"https://www.nobelprize.org/prizes/chemistry/2024/hassabis/interview/"},
  {date:"2022-07-01",type:"interview",text:"Demis Hassabis on Lex Fridman #299 — Superintelligence & DeepMind",company:"deepmind",link:"https://lexfridman.com/demis-hassabis/"},
  {date:"2017-01-01",type:"interview",text:"Demis Hassabis on BBC Desert Island Discs",company:"deepmind",link:"https://www.bbc.co.uk/programmes/b08qy1sl"},
  // Dario Amodei
  {date:"2026-02-01",type:"interview",text:"Dario Amodei on Dwarkesh Patel — 'We are near the end of the exponential'",company:"anthropic",link:"https://www.dwarkesh.com/p/dario-amodei-2"},
  {date:"2024-11-01",type:"interview",text:"Dario Amodei on Lex Fridman #452 — Claude, AGI & Future of AI (5h)",company:"anthropic",link:"https://www.youtube.com/watch?v=ugvHCXCOmm4"},
  {date:"2025-01-01",type:"interview",text:"Dario Amodei — In Good Company with Nicolai Tangen (Norwegian SWF)",company:"anthropic",link:"https://open.spotify.com/episode/6UzOVEv3Upt5oHAMZw9Gzx"},
  {date:"2023-08-01",type:"interview",text:"Dario Amodei on Dwarkesh Patel — $10 Billion Models, OpenAI & Scaling",company:"anthropic",link:"https://www.dwarkesh.com/p/dario-amodei"},
  // Sam Altman
  {date:"2025-10-01",type:"interview",text:"Sam Altman on Conversations with Tyler — second appearance",company:"openai",link:"https://conversationswithtyler.com/episodes/sam-altman-2/"},
  {date:"2025-04-01",type:"interview",text:"Sam Altman TED 2025 — ChatGPT, AI Agents & Superintelligence",company:"openai",link:"https://www.ted.com/talks/sam_altman_openai_s_sam_altman_talks_chatgpt_ai_agents_and_superintelligence_live_at_ted2025"},
  {date:"2024-03-01",type:"interview",text:"Sam Altman on Lex Fridman #419 — GPT-5, Sora, Board Saga",company:"openai",link:"https://lexfridman.com/sam-altman-2/"},
  {date:"2024-05-01",type:"interview",text:"Sam Altman on All-In Podcast — In Conversation",company:"openai",link:"https://open.spotify.com/episode/0rka7b2zunmx6f0etLWRGB"},
  {date:"2023-10-01",type:"interview",text:"Sam Altman on Joe Rogan #2044",company:"openai",link:"https://open.spotify.com/episode/66edV3LAbUXa26HG1ZQaKB"},
  {date:"2023-03-01",type:"interview",text:"Sam Altman on Lex Fridman #367 — GPT-4, ChatGPT & the Future",company:"openai",link:"https://lexfridman.com/sam-altman/"},
  // Arthur Mensch
  {date:"2026-02-18",type:"interview",text:"Arthur Mensch on CNBC — India AI Impact Summit",company:"mistral",link:"https://www.cnbc.com/video/2026/02/18/watch-cnbcs-full-interview-with-mistral-ai-ceo-arthur-mensch.html"},
  {date:"2025-09-09",type:"interview",text:"Arthur Mensch on CNBC Squawk Box — Mistral funding & strategy",company:"mistral",link:"https://www.cnbc.com/video/2025/09/09/watch-cnbcs-full-interview-with-mistral-ai-founder-and-ceo-arthur-mensch.html"},
  {date:"2023-10-01",type:"interview",text:"Arthur Mensch on No Priors #40 — Mistral 7B & Open Source Revolution",company:"mistral",link:"https://open.spotify.com/episode/2H7gV2CgfzS7jXK4Mx8v9j"},
  {date:"2024-03-01",type:"interview",text:"Arthur Mensch — TIME Magazine: Europe's AI Ecosystem",company:"mistral",link:"https://time.com/7007040/mistral-ai-ceo-arthur-mensch-interview/"},
  // Aidan Gomez
  {date:"2024-10-01",type:"interview",text:"Aidan Gomez on No Priors #91 — Model Plateaus & Enterprise AI",company:"cohere",link:"https://open.spotify.com/episode/4ALfoL5D1bujniynuy76yM"},
  {date:"2025-02-01",type:"interview",text:"Aidan Gomez on MAD Podcast — The Paper That Changed AI Forever",company:"cohere",link:"https://open.spotify.com/episode/70RgbeBY38bhP4wSshSEGW"},
  {date:"2024-06-01",type:"interview",text:"Aidan Gomez on MLST — AI's Inner Monologue for Reasoning",company:"cohere",link:"https://open.spotify.com/episode/0oFwBJG0lBdbBaHK1M8L8H"},
  // Alex Kendall
  {date:"2025-11-01",type:"interview",text:"Alex Kendall on Sequoia Training Data — End-to-End AV 2.0",company:"wayve",link:"https://sequoiacap.com/podcast/how-end-to-end-learning-created-autonomous-driving-2-0-wayve-ceo-alex-kendall/"},
  {date:"2024-05-07",type:"interview",text:"Alex Kendall on TechCrunch — Autonomous Future for Cars & Robots",company:"wayve",link:"https://techcrunch.com/2024/05/07/exclusive-wayve-cofounder-alex-kendall-on-the-autonomous-future-for-cars-and-robots/"},
  {date:"2023-06-01",type:"interview",text:"Alex Kendall on Sifted Podcast — Vindicated by Elon Musk",company:"wayve",link:"https://sifted.eu/articles/wayves-alex-kendall-sifted-podcast"},
  // Victor Riparbelli
  {date:"2026-01-13",type:"interview",text:"Victor Riparbelli on CNBC Executive Decisions — Synthesia at $4B",company:"synthesia",link:"https://www.cnbc.com/video/2026/01/13/synthesia-ceo-victor-riparbelli-executive-decisions-with-steve-sedgwick.html"},
  {date:"2024-09-01",type:"interview",text:"Victor Riparbelli on 20VC E1246 — OpenAI vs Anthropic: Who Wins",company:"synthesia",link:"https://open.spotify.com/episode/4Qe1XP4sPOLBZ8tAA4P0Er"},
  {date:"2025-01-01",type:"interview",text:"Victor Riparbelli on This Week in Startups — $1B AI Avatar Business",company:"synthesia",link:"https://thisweekinstartups.com/episodes/EbY2M03ANMs"},
  {date:"2024-06-01",type:"interview",text:"Victor Riparbelli on Accel Spotlight On — AI Benefits & Harms",company:"synthesia",link:"https://www.accel.com/podcast-episodes/synthesia-victor-riparbelli"},
  // Mati Staniszewski
  {date:"2025-11-01",type:"interview",text:"Mati Staniszewski on Sequoia — Scaling AI Rocketships (ElevenLabs)",company:"elevenlabs",link:"https://sequoiacap.com/podcast/scaling-ai-rocketships-elevenlabs-mati-staniszewski-lovables-anton-osika/"},
  {date:"2025-09-01",type:"interview",text:"Mati Staniszewski on 20VC — ElevenLabs hits $200M ARR",company:"elevenlabs",link:"https://open.spotify.com/episode/12pXbRQVhbx91MyBydH64i"},
  {date:"2026-01-12",type:"interview",text:"Mati Staniszewski on Bloomberg TV — $330M ARR crossed",company:"elevenlabs",link:"https://www.bloomberg.com/news/videos/2026-01-12/elevenlabs-330m-crossed-in-arr-video"},
  // Connor Leahy
  {date:"2023-07-01",type:"interview",text:"Connor Leahy on Future of Life Institute — Why Humanity Risks Extinction from AGI",company:"conjecture",link:"https://futureoflife.org/podcast/connor-leahy-on-why-humanity-risks-extinction-from-agi/"},
  {date:"2023-12-01",type:"interview",text:"Connor Leahy vs Beff Jezos on MLST — e/acc vs Doomer Showdown",company:"conjecture",link:"https://www.youtube.com/watch?v=0zxi0xSBOaQ"},
  {date:"2023-05-01",type:"interview",text:"Connor Leahy on FLI — AGI & Cognitive Emulation",company:"conjecture",link:"https://futureoflife.org/podcast/connor-leahy-on-agi-and-cognitive-emulation/"},
  // Yann LeCun
  {date:"2024-03-01",type:"interview",text:"Yann LeCun on Lex Fridman #416 — Meta AI, Open Source, Limits of LLMs",company:"meta-ai",link:"https://lexfridman.com/yann-lecun-3/"},
  {date:"2021-06-01",type:"interview",text:"Yann LeCun TED Talk — Deep Learning & Future of AI",company:"meta-ai",link:"https://www.ted.com/talks/yann_lecun_deep_learning_neural_networks_and_the_future_of_ai"},
  {date:"2022-02-01",type:"interview",text:"Yann LeCun on Lex Fridman #258 — Dark Matter of Intelligence",company:"meta-ai",link:"https://lexfridman.com/yann-lecun-2/"},
  // Mustafa Suleyman
  {date:"2025-12-01",type:"interview",text:"Mustafa Suleyman on Bloomberg — 'AI Is Already Superhuman'",company:"ms-research",link:"https://www.bloomberg.com/features/2025-mustafa-suleyman-weekend-interview/"},
  {date:"2024-04-01",type:"interview",text:"Mustafa Suleyman TED 2024 — What is an AI Anyway?",company:"ms-research",link:"https://www.youtube.com/watch?v=KKNCiRWd_j0"},
  {date:"2025-04-04",type:"interview",text:"Mustafa Suleyman on CNBC Closing Bell — Microsoft AI CEO",company:"ms-research",link:"https://www.cnbc.com/video/2025/04/04/watch-cnbcs-full-interview-with-microsoft-ai-ceo-mustafa-suleyman.html"},
  // David Silver
  {date:"2019-01-01",type:"interview",text:"David Silver — Lex Fridman #86: AlphaGo, AlphaZero & Deep RL",company:"deepmind",link:"https://www.youtube.com/watch?v=uPUEq8d73JI"},
  {date:"2015-01-01",type:"interview",text:"David Silver — UCL RL Course Lecture 1 (legendary, millions of views)",company:"deepmind",link:"https://www.youtube.com/watch?v=2pWv7GOvuf0"},
  // Nathan Benaich
  {date:"2025-11-01",type:"interview",text:"Nathan Benaich on Hidden Forces #448 — State of AI 2025 & Investing",company:"air-street",link:"https://hiddenforces.io/podcasts/investing-on-the-front-lines-of-the-ai-arms-race-nathan-benaich/"},
  {date:"2025-10-01",type:"interview",text:"Nathan Benaich — State of AI 2025 Report Launch (video + 300 slides)",company:"air-street",link:"https://www.stateof.ai/2025-report-launch"},
  {date:"2024-11-01",type:"interview",text:"Nathan Benaich on The PEEL — 2-hour State of AI deep dive",company:"air-street",link:"https://www.thespl.it/p/the-state-of-ai-with-nathan-benaich"},
  // Ian Hogarth
  {date:"2023-06-01",type:"interview",text:"Ian Hogarth on AI Breakdown — Head of UK AI Taskforce",company:"plural",link:"https://podcasts.apple.com/us/podcast/what-the-head-of-the-new-uk-ai-foundation/id1680633614?i=1000618244541"},
  {date:"2023-09-01",type:"interview",text:"Ian Hogarth — TIME 100 AI profile & interview",company:"plural",link:"https://time.com/collection/time100-ai/6309473/ian-hogarth/"},
  {date:"2019-01-01",type:"interview",text:"Ian Hogarth on Sifted — 'Machine learning will eat the world'",company:"plural",link:"https://sifted.eu/articles/ian-hogarth-machine-learning-will-eat-the-world"},
  // Poppy Gustafsson
  {date:"2021-05-01",type:"interview",text:"Poppy Gustafsson — TIME Leadership Brief: Fighting Cyber Attacks",company:"darktrace",link:"https://time.com/6048319/poppy-gustafsson-darktrace-cyber-attacks/"},
  {date:"2019-06-01",type:"interview",text:"Poppy Gustafsson at BoS Europe — Scaling AI at Warp Speed",company:"darktrace",link:"https://businessofsoftware.org/talks/billion-dollar-business/"},
  // Torsten Reil
  {date:"2025-10-21",type:"interview",text:"Torsten Reil on Bloomberg Tech Summit — AI's Role in Defence",company:"helsing",link:"https://www.bloomberg.com/news/videos/2025-10-21/helsing-s-reil-on-ai-s-role-in-defense-innovation-video"},
  {date:"2025-06-01",type:"interview",text:"Torsten Reil on 20VC — Raising $828M for European Defence AI",company:"helsing",link:"https://www.thetwentyminutevc.com/torsten-reil"},
  {date:"2025-03-23",type:"interview",text:"Torsten Reil — FT Lunch: AI Drones, Ukraine & VC Herd Mentality",company:"helsing",link:"https://www.techmeme.com/250323/p11"},
  // Nikola Mrksic
  {date:"2024-06-01",type:"interview",text:"Nikola Mrkšić on Practical AI — Next-Gen Voice Assistants",company:"polyai",link:"https://poly.ai/blog/nikola-mrksic-on-the-practical-ai-podcast/"},
  {date:"2025-02-19",type:"interview",text:"Nikola Mrkšić on tech.eu — 'Our future is predominantly American'",company:"polyai",link:"https://tech.eu/2025/02/19/our-future-is-predominantly-american-says-founder-of-nvidia-backed-london-startup-polyai/"},
  // Guy Podjarny
  {date:"2025-03-01",type:"interview",text:"Guy Podjarny on Scaling DevTools — Future of Programming (Tessl)",company:"tessl",link:"https://scalingdevtools.com/podcast/episodes/guy-podjarny"},
  {date:"2024-06-01",type:"interview",text:"Guy Podjarny on PMF Show — Snyk $4M to $4.5M ARR story",company:"tessl",link:"https://www.pmf.show/guy-podjarny-snyk-product-buyer-fit-growth/"},
  // Barney Hussey-Yeo
  {date:"2024-11-01",type:"interview",text:"Barney Hussey-Yeo on Jimmy's Jobs — UK Unicorns: Cleo",company:"cleo",link:"https://open.spotify.com/episode/4kX02ccyFWYXgsFmEa1nOA"},
  {date:"2024-03-01",type:"interview",text:"Barney Hussey-Yeo on Sifted — Build £100bn & Save Democracy",company:"cleo",link:"https://sifted.eu/articles/cleo-big-interview"},
  // Alex Dalyac
  {date:"2021-09-01",type:"interview",text:"Alex Dalyac on EF Podcast — Billion Dollar Tractable Story (w/ Reid Hoffman)",company:"tractable",link:"https://podcasts.apple.com/gb/podcast/the-billion-dollar-story-of-tractable/id1581333327?i=1000533165537"},
  {date:"2022-02-01",type:"interview",text:"Alex Dalyac on World of DaaS — Building a Computer Vision Unicorn",company:"tractable",link:"https://podcasts.apple.com/us/podcast/alex-dalyac-the-secret-to-building-a-computer/id1570644971?i=1000551139486"},
];

// ── COMPANIES ───────────────────────────────────────────────────────────
export const companies=[
  {id:"deepmind",name:"Google DeepMind",s:"DeepMind",cat:"frontier",yr:2010,emp:"~3,000 LDN",fund:"$500-650M (acq.)",fn:600,val:"Alphabet sub.",founders:"Demis Hassabis, Shane Legg, Mustafa Suleyman",focus:"AGI · AlphaFold · Gemini · RL · robotics",ethos:"Solve intelligence",hq:"King's Cross",kp:"Hassabis (CEO, Nobel '24), Legg (Chief Sci), Kavukcuoglu (VP Res)",ms:"AlphaGo '16 · AlphaFold '20 · Gemini '23 · Nobel '24",jobs:"https://deepmind.google/careers/"},
  {id:"anthropic",name:"Anthropic",s:"Anthropic",cat:"frontier",yr:2021,emp:"1,000+",fund:"~$30B",fn:30000,val:"$380B",founders:"Dario & Daniela Amodei",focus:"AI safety · Constitutional AI · Claude",ethos:"Safety-first",hq:"Cheapside (LDN)",kp:"Pip White (EMEA N), Guillaume Princen (EMEA)",ms:"LDN '23 · Claude 3.5 · 100+ UK roles",jobs:"https://www.anthropic.com/careers"},
  {id:"openai",name:"OpenAI",s:"OpenAI",cat:"frontier",yr:2015,emp:"92-300 LDN",fund:"$17B+",fn:17000,val:"$157B+",founders:"Sam Altman et al.",focus:"GPT · ChatGPT · DALL-E · Sora · o1",ethos:"AGI for all",hq:"King's Cross",kp:"Altman (CEO)",ms:"LDN '23 · UK MoU '25 · Humphrey AI",jobs:"https://openai.com/careers/"},
  {id:"meta-ai",name:"Meta AI / FAIR",s:"Meta AI",cat:"frontier",yr:2013,emp:"~3,000",fund:"Meta sub.",fn:0,val:"Meta sub.",founders:"Yann LeCun",focus:"Llama · CV · open-source",ethos:"Open AI",hq:"LDN research",kp:"Fergus (FAIR, ex-DM)",ms:"Llama 3 · LeCun→AMI Labs",jobs:"https://www.metacareers.com/"},
  {id:"ms-research",name:"Microsoft Research",s:"MS Research",cat:"frontier",yr:1997,emp:"6,000 UK",fund:"MS sub.",fn:0,val:"MS sub.",founders:"Needham '97",focus:"ML · AI science · security",ethos:"Empower",hq:"Cambridge+Paddington",kp:"Suleyman (MS AI CEO), Hoffmann (LDN Hub)",ms:"$30B UK · Paddington Hub · UK supercomputer",jobs:"https://www.microsoft.com/en-us/research/careers/"},
  {id:"mistral",name:"Mistral AI",s:"Mistral",cat:"frontier",yr:2023,emp:"280+",fund:"€486M+",fn:550,val:"€5.8B",founders:"Mensch (ex-DM), Lample, Lacroix (ex-Meta)",focus:"Open LLMs · enterprise",ethos:"EU sovereignty",hq:"Paris (LDN sat.)",kp:"Mensch (CEO)",ms:"Mistral 7B · Mixtral · Le Chat",jobs:"https://jobs.lever.co/mistral/"},
  {id:"cohere",name:"Cohere",s:"Cohere",cat:"frontier",yr:2019,emp:"500 (50 LDN)",fund:"~$1B",fn:1000,val:"$5.5B+",founders:"Gomez (Attention, Oxford), Zhang, Frosst",focus:"Enterprise NLP · North",ethos:"Enterprise, cloud-agnostic",hq:"Toronto (LDN hub)",kp:"Gomez (CEO), Blunsom (Sci, ex-Oxford), Pineau (CAO)",ms:"Pineau hire · doubling LDN",jobs:"https://jobs.ashbyhq.com/cohere"},
  {id:"wayve",name:"Wayve",s:"Wayve",cat:"autonomous",yr:2017,emp:"350+",fund:"~$2.5B",fn:2500,val:"$8.6B",founders:"Alex Kendall (Cambridge/OBE)",focus:"End-to-end AV · no lidar",ethos:"AI-first driving",hq:"London",kp:"Kendall (CEO), Shotton (Sci, ex-MS)",ms:"$1.2B D '26 · Uber L4 · Nissan '27",jobs:"https://wayve.ai/careers/"},
  {id:"synthesia",name:"Synthesia",s:"Synthesia",cat:"generative",yr:2017,emp:"400+",fund:"~$530M",fn:530,val:"$4B",founders:"Riparbelli, Tjerrild, Niessner, Agapito",focus:"AI video · avatars · 140+ langs",ethos:"Ethics-first",hq:"London",kp:"Riparbelli (CEO)",ms:"$200M E '26 · $100M ARR · 80% F100",jobs:"https://www.synthesia.io/careers"},
  {id:"isomorphic",name:"Isomorphic Labs",s:"Isomorphic",cat:"biotech",yr:2021,emp:"200+",fund:"$600M",fn:600,val:"Alphabet sub.",founders:"Demis Hassabis",focus:"AI drug discovery",ethos:"Solve all disease",hq:"King's Cross",kp:"Hassabis (CEO), Jaderberg (CTO)",ms:"$600M A '25 · Lilly/Novartis $3B",jobs:"https://www.isomorphiclabs.com/careers"},
  {id:"elevenlabs",name:"ElevenLabs",s:"ElevenLabs",cat:"generative",yr:2022,emp:"330",fund:"$781M",fn:781,val:"$11B",founders:"Staniszewski (Imperial), Dąbkowski (ex-DM)",focus:"AI voice · TTS · 70+ langs",ethos:"Break language barriers",hq:"Soho + Warsaw",kp:"Staniszewski (CEO), Dąbkowski (CTO)",ms:"$500M D '26 · $330M ARR · IPO talk",jobs:"https://elevenlabs.io/careers"},
  {id:"stability",name:"Stability AI",s:"Stability",cat:"generative",yr:2019,emp:"~190",fund:"~$300M",fn:300,val:"$1B",founders:"Mostaque (departed '24)",focus:"Open image/video gen",ethos:"Open generative AI",hq:"Notting Hill",kp:"Akkaraju (CEO), Parker (Chair)",ms:"Stable Diffusion '22 · rescue '24",jobs:"https://stability.ai/careers"},
  {id:"helsing",name:"Helsing",s:"Helsing",cat:"defence",yr:2021,emp:"275-500",fund:"€1.37B",fn:1500,val:"€12B",founders:"Reil, Scherf",focus:"Military AI · drones",ethos:"Democratic defence",hq:"Munich (LDN)",kp:"Gould (UK MD)",ms:"€600M D · AI fighter pilot · FCAS",jobs:"https://helsing.ai/careers"},
  {id:"darktrace",name:"Darktrace",s:"Darktrace",cat:"defence",yr:2013,emp:"2,400+",fund:"$230M",fn:230,val:"$5.3B",founders:"Gustafsson, Stockdale, Eagan",focus:"Self-learning cyber AI",ethos:"Immune system",hq:"Cambridge+LDN",kp:"Gustafsson (UK Min.)",ms:"IPO '21 · TB $5.3B '24",jobs:"https://darktrace.com/careers"},
  {id:"graphcore",name:"Graphcore",s:"Graphcore",cat:"hardware",yr:2016,emp:"~500",fund:"$710M",fn:710,val:"SB acq.",founders:"Toon, Knowles, Hauser",focus:"IPUs",ethos:"AI silicon",hq:"Bristol+LDN",kp:"Toon (CEO)",ms:"SB acq. '24",jobs:"https://www.graphcore.ai/careers"},
  {id:"faculty",name:"Faculty AI",s:"Faculty",cat:"enterprise",yr:2014,emp:"400",fund:"~£40M",fn:50,val:"~$1B (Accenture)",founders:"Dr Warner, Dr Ma",focus:"Decision intel · govt AI",ethos:"AI for institutions",hq:"London",kp:"Warner (→Accenture CTO)",ms:"Accenture acq. '26",jobs:"https://faculty.ai/careers/"},
  {id:"benevolentai",name:"BenevolentAI",s:"BenevolentAI",cat:"biotech",yr:2013,emp:"~69",fund:"$700M+",fn:700,val:"€1.5B peak",founders:"Mulvany",focus:"AI drug discovery",ethos:"Cure disease",hq:"Fitzrovia",kp:"Mulvany (Chair)",ms:"COVID baricitinib · delisted '25",jobs:"https://www.benevolent.com/careers"},
  {id:"polyai",name:"PolyAI",s:"PolyAI",cat:"enterprise",yr:2017,emp:"200+",fund:"$206M",fn:206,val:"$500M+",founders:"Mrkšić, Wen, Su (Cambridge)",focus:"Voice AI agents · 45 langs",ethos:"Human-quality voice",hq:"Holborn",kp:"Mrkšić (CEO)",ms:"$86M D '25 · FedEx/Marriott",jobs:"https://poly.ai/careers/"},
  {id:"cleo",name:"Cleo AI",s:"Cleo",cat:"fintech",yr:2016,emp:"300-500",fund:"~$175M",fn:175,val:"$500M+",founders:"Barney Hussey-Yeo",focus:"AI money assistant",ethos:"Money + sass",hq:"London+NYC",kp:"Hussey-Yeo (CEO)",ms:"$300M+ ARR · profitable · 6M users",jobs:"https://web.meetcleo.com/careers"},
  {id:"tractable",name:"Tractable",s:"Tractable",cat:"enterprise",yr:2014,emp:"117-224",fund:"$185M",fn:185,val:"$1B",founders:"Dalyac, Ranca, Cohen",focus:"CV insurance damage",ethos:"Accelerate recovery",hq:"London",kp:"Dalyac (CEO)",ms:"1st CV unicorn · $7B+ repairs/yr",jobs:"https://tractable.ai/careers/"},
  {id:"signal-ai",name:"Signal AI",s:"Signal AI",cat:"enterprise",yr:2013,emp:"220+",fund:"$268M",fn:268,val:"Undisclosed",founders:"Benigson, Martinez, Hall",focus:"External intel · 226 markets",ethos:"Decision augmentation",hq:"London",kp:"Benigson (CEO)",ms:"$165M Battery '25",jobs:"https://www.signal-ai.com/careers"},
  {id:"abound",name:"Abound",s:"Abound",cat:"fintech",yr:2020,emp:"100-130",fund:"£1.6B+",fn:150,val:"Undisclosed",founders:"Chappell, He",focus:"AI lending",ethos:"Fair credit",hq:"London",kp:"Chappell (CEO)",ms:"Profitable '24",jobs:"https://www.getabound.com/careers"},
  {id:"exscientia",name:"Exscientia",s:"Exscientia",cat:"biotech",yr:2012,emp:"~250",fund:"$674M",fn:674,val:"$2.9B",founders:"Hopkins CBE",focus:"1st AI drug in trials",ethos:"Precision med",hq:"Oxford",kp:"Hopkins (CEO)",ms:"Recursion acq. '24",jobs:null},
  {id:"onfido",name:"Onfido→Entrust",s:"Onfido",cat:"enterprise",yr:2012,emp:"600+",fund:"$242M",fn:242,val:"$1.5B",founders:"Kassai, Jubbawy, Amin (Oxford)",focus:"AI identity · 195 countries",ethos:"Identity for all",hq:"LDN→Entrust",kp:"Kassai→AI Hub",ms:"Entrust $650M '24",jobs:null},
  {id:"ineffable",name:"Ineffable Intelligence",s:"Ineffable",cat:"frontier-emerging",yr:2025,emp:"Early",fund:"Seeking $1B",fn:0,val:"~$4B",founders:"David Silver (DM, AlphaGo)",focus:"RL superintelligence",ethos:"Beyond LLMs",hq:"London",kp:"Silver",ms:"Founded Nov '25",jobs:null},
  {id:"tessl",name:"Tessl",s:"Tessl",cat:"devtools",yr:2024,emp:"Early",fund:"$125M",fn:125,val:"$750M",founders:"Podjarny (Snyk $7.4B)",focus:"AI-native dev",ethos:"Spec-driven",hq:"London",kp:"Podjarny (CEO)",ms:"$125M pre-product",jobs:"https://www.tessl.io/careers"},
  {id:"solveai",name:"SolveAI",s:"SolveAI",cat:"enterprise",yr:2025,emp:"12",fund:"$50M",fn:50,val:"Undisclosed",founders:"Steve Basher (ex-Palantir 8yr)",focus:"Enterprise AI no-code · natural language → production apps",ethos:"Democratise enterprise software",hq:"Chancery Lane, London",kp:"Basher (CEO)",ms:"$45M A (GV) + $5M pre-seed (Accel) · Feb 2026 · 7mo old · Palantir/ElevenLabs/Meta team",jobs:"https://www.solve.ai/careers"},
  {id:"sovereign-ai",name:"Sovereign AI",s:"SovAI",cat:"investor",yr:2026,emp:"—",fund:"£500M",fn:500,val:"Gov fund",founders:"DSIT / James Wise (Balderton)",focus:"UK gov £500M AI venture fund · backing British AI founders from seed",ethos:"Start here, scale here, win everywhere",hq:"London",kp:"James Wise (Chair)",ms:"Launching Apr 16 2026 · DSIT-backed · sovereign compute + startup investment",jobs:"https://sovereignai.gov.uk/"},
  {id:"thrive",name:"Thrive Capital",s:"Thrive",cat:"investor",yr:2009,emp:null,fund:null,fn:0,val:null,founders:"Josh Kushner",focus:"Early & growth VC · AI infrastructure · developer tools · $10B+ AUM",ethos:"Backing the future",hq:"New York",kp:"Josh Kushner",ms:"Led Isomorphic Labs $600M A · OpenAI investor",jobs:null},
  {id:"battery",name:"Battery Ventures",s:"Battery",cat:"investor",yr:1983,emp:null,fund:null,fn:0,val:null,founders:null,focus:"Growth & late-stage VC · enterprise software · AI · $13B+ deployed",ethos:null,hq:"Boston / London",kp:"Michael Brown, Neeraj Agrawal",ms:"Led Signal AI $165M",jobs:null},
  {id:"georgian",name:"Georgian",s:"Georgian",cat:"investor",yr:2008,emp:null,fund:null,fn:0,val:null,founders:null,focus:"Growth VC · applied AI & ML · $4B+ AUM",ethos:null,hq:"Toronto",kp:"Justin LaFayette, Simon Fong",ms:"Led PolyAI $86M Series D",jobs:null},
  {id:"nscale",name:"Nscale",s:"Nscale",cat:"hardware",yr:2021,emp:"Growing",fund:"$2B+",fn:2000,val:"$14.6B",founders:"Josh Payne (CEO & Founder)",focus:"AI infrastructure hyperscaler · GPU compute · data centres · training & inference at scale",ethos:"Engine of superintelligence",hq:"London (Loughton DC) + Norway + US",kp:"Josh Payne (CEO), Sheryl Sandberg (Board), Nick Clegg (Board)",ms:"$2B Series C (Mar 2026, largest in European history) · Led by Aker ASA & 8090 Industries · Investors: Citadel, Dell, Jane Street, Lenovo, Nokia, NVIDIA, Point72 · JPM & Goldman placement agents",jobs:"https://www.nscale.com/careers"},
  {id:"isembard",name:"Isembard",s:"Isembard",cat:"defence",yr:2025,emp:"Growing",fund:"$50M",fn:50,val:"Undisclosed",founders:"Alexander Fitzgerald (CEO & Founder)",focus:"AI-powered precision manufacturing · MasonOS agentic factory OS · aerospace & defence components · franchise model",ethos:"Forge industrial acceleration",hq:"UK + expanding to Germany, France, Ukraine",kp:"Alexander Fitzgerald (CEO)",ms:"$50M Series A (Mar 2026) · Led by Union Square Ventures · IQ Capital, Notion Capital, Tamarack Global, CIV · Angels: Alex Bouaziz (Deel), Andrei Danescu (Dexory), Matt Briers (ex-Wise CFO) · 25 factories planned by end 2026",jobs:"https://www.isembard.com/careers"},
  {id:"mutable-tactics",name:"Mutable Tactics",s:"Mutable Tactics",cat:"defence",yr:2024,emp:"Early",fund:"$2M",fn:2,val:"Undisclosed",founders:"Enrique Munoz de Cote & Colin MacLeod",focus:"AI-powered autonomous mission systems for UAVs · real-time decision-making in defence operations",ethos:"Autonomous defence",hq:"London",kp:"Enrique Munoz de Cote, Colin MacLeod",ms:"$2M Pre-Seed (Mar 2026, Seraphim Space)",jobs:null},
  {id:"callosum",name:"Callosum",s:"Callosum",cat:"hardware",yr:2024,emp:"Early",fund:"$10.25M",fn:10,val:"Undisclosed",founders:"Danyal Akarca & Jascha Achterberg (Cambridge neuroscience PhDs)",focus:"Multi-chip AI orchestration · heterogeneous inference across NVIDIA, AMD, AWS Trainium, Cerebras, SambaNova · sovereign compute",ethos:"Intelligence is heterogeneous",hq:"London",kp:"Danyal Akarca (CEO), Jascha Achterberg (CTO)",ms:"$10.25M Seed (Feb 2026, Plural) · ARIA UK gov research funding · Scaling Inference Lab · 2x accuracy, 7x speed, 4x cost reduction",jobs:"https://www.callosum.com/join-us"},
  {id:"olix",name:"OLIX",s:"OLIX",cat:"hardware",yr:2024,emp:"Growing",fund:"$250M",fn:250,val:"Undisclosed",founders:"James Dacombe",focus:"Optical AI accelerators · light-based processors for training & inference · photonic computing",ethos:"Light-speed AI",hq:"London",kp:"James Dacombe (Founder)",ms:"$220M Series A (Feb 2026) · Octopus Ventures, LocalGlobe, EF, Vertex, Crane, Plural, Hummingbird",jobs:null},
  {id:"trace",name:"Trace",s:"Trace",cat:"enterprise",yr:2025,emp:"Early",fund:"$3M",fn:3,val:"Undisclosed",founders:"Tim Cherkasov (CEO, ex-Copper) & Artur Romanov (CTO, ex-Deliveroo)",focus:"AI agent workflow orchestration · maps corporate knowledge graphs so agents have context to scale",ethos:"The manager for AI interns",hq:"London",kp:"Tim Cherkasov (CEO), Artur Romanov (CTO)",ms:"$3M Seed (Feb 2026) · Y Combinator S25 · Zeno Ventures, Goodwater Capital",jobs:"https://www.trace.so/"},
  {id:"finster",name:"Finster AI",s:"Finster",cat:"fintech",yr:2023,emp:"Growing",fund:"$15M",fn:15,val:"Undisclosed",founders:"Sid Jayakumar (ex-DeepMind 7yr)",focus:"AI-native financial intelligence · investment research · task automation for banks & asset managers",ethos:"Redefine financial intelligence",hq:"London + New York",kp:"Jayakumar (CEO), Chris Andrews (COO, ex-Morgan Stanley), Veeral Manek (ex-Revolut)",ms:"$15M A+Seed (FinTech Collective + Peak XV) · Oct 2025 · Tier 1 IB clients · Third Bridge/Preqin/MT Newswires partnerships",jobs:"https://job-boards.eu.greenhouse.io/finsterai"},
  {id:"vivox-ai",name:"Vivox AI",s:"Vivox AI",cat:"fintech",yr:2024,emp:"Early",fund:"£1.3M",fn:2,val:"Undisclosed",founders:"Tim Khamzin",focus:"Agentic platform for pre-trained AI agents · AML, KYB, financial crime compliance",ethos:"AI agents for compliance",hq:"London",kp:"Tim Khamzin (Founder)",ms:"£1.3M Venture (Mar 2026) · Angels: Axel Weber (ex-Bundesbank), Dan Cobley (ex-Google UK)",jobs:null},
  {id:"condukt",name:"Condukt",s:"Condukt",cat:"fintech",yr:2023,emp:"Growing",fund:"Undisclosed",fn:5,val:"Undisclosed",founders:"Paulo & Bhasker (Baz)",focus:"AI compliance for fintechs · real-time KYB · agentic workflows · clients: Wise, Tide, Mollie, Revolut",ethos:"Compliance at the speed of business",hq:"London",kp:"Paulo (CEO), Bhasker (CRO)",ms:"MMC + Lightspeed invested · Clients: Wise, Tide, Mollie, Rakuten, Shift4, myPOS",jobs:null},
  {id:"blackwall",name:"Blackwall",s:"Blackwall",cat:"enterprise",yr:2019,emp:"Growing",fund:"Undisclosed",fn:5,val:null,founders:null,focus:"AI bot protection · web security · protecting ecosystems from automated threats",ethos:"Protecting the web",hq:"London",kp:null,ms:"MMC invested 2025",jobs:null},
  {id:"nexcade",name:"Nexcade",s:"Nexcade",cat:"enterprise",yr:2024,emp:"Early",fund:"$2.5M",fn:3,val:null,founders:"Dan Bailey & Tasho Kjosev",focus:"AI automation for freight forwarders · agentic orchestration · quote/rate/booking automation",ethos:"Automating global freight",hq:"London",kp:"Dan Bailey (CEO), Tasho Kjosev (CTO)",ms:"$2.5M Pre-Seed (Oct 2025, Connect Ventures + MMC) · Clients: Zencargo, XPO",jobs:null},
  {id:"physicsx",name:"PhysicsX",s:"PhysicsX",cat:"enterprise",yr:2023,emp:"150+",fund:"~$175M",fn:175,val:"~$1B",founders:"Tuluie, Corbo",focus:"Large Physics Models",ethos:"AI engineering",hq:"London",kp:"Tuluie (CEO)",ms:"$135M B '25 Atomico",jobs:"https://physicsx.com/careers"},
  {id:"conjecture",name:"Conjecture",s:"Conjecture",cat:"safety",yr:2021,emp:"~13",fund:"~$25M",fn:25,val:"Undisclosed",founders:"Leahy (EleutherAI)",focus:"Cognitive Emulation",ethos:"Safe before powerful",hq:"London",kp:"Leahy (CEO)",ms:"Karpathy/Collisons angels",jobs:"https://www.conjecture.dev/careers"},
  {id:"holistic-ai",name:"Holistic AI",s:"Holistic AI",cat:"safety",yr:2020,emp:"43-79",fund:"$15M+",fn:15,val:"Undisclosed",founders:"Koshiyama, Kazim (UCL)",focus:"AI governance · EU AI Act",ethos:"Responsible AI",hq:"Soho Sq",kp:"Koshiyama (CEO)",ms:"500+ clients",jobs:"https://www.holisticai.com/careers"},
  {id:"albatross-ai",name:"Albatross AI",s:"Albatross",cat:"enterprise",yr:2025,emp:"Early",fund:"$12.5M",fn:13,val:"Undisclosed",founders:"",focus:"Foundational AI for real-time content discovery",ethos:"Real-time discovery",hq:"London",kp:"",ms:"$12.5M Seed (Nov 2025, MMC + Redalpine + Daphni)",jobs:null},
  {id:"peak-ai",name:"Peak AI",s:"Peak",cat:"enterprise",yr:2014,emp:"200+",fund:"$118M",fn:118,val:"Exited",founders:"Richard Potter",focus:"Decision Intelligence · AI for enterprise decision-making · inventory, pricing, CRM",ethos:"AI for better decisions",hq:"London / Manchester",kp:"Richard Potter (CEO)",ms:"$75M Series C (2022) · Acquired by UiPath (2025)",jobs:null},
  {id:"encord",name:"Encord",s:"Encord",cat:"devtools",yr:2020,emp:"50+",fund:"~€50M+",fn:55,val:"Undisclosed",founders:"Landau, Hansen",focus:"AI data annotation",ethos:"Data-centric",hq:"London",kp:"Landau (CEO)",ms:"€50M C '26",jobs:"https://encord.com/careers/"},
  {id:"convergence",name:"Convergence→Salesforce",s:"Convergence",cat:"enterprise",yr:2024,emp:"Acq.",fund:"$12M",fn:12,val:"Acq.",founders:"Purtorab, Toulis",focus:"AI agents + memory",ethos:"AI that remembers",hq:"LDN→SF",kp:null,ms:"SF acq. 9mo",jobs:null},
  {id:"latent-labs",name:"Latent Labs",s:"Latent Labs",cat:"biotech",yr:2025,emp:"Early",fund:"$50M",fn:50,val:"Undisclosed",founders:"Kohl (AlphaFold2, DM)",focus:"AI protein design",ethos:"Design biology",hq:"London",kp:"Kohl (CEO)",ms:"1st model Jul '25",jobs:null},
  {id:"fyxer",name:"Fyxer AI",s:"Fyxer",cat:"enterprise",yr:2024,emp:"Growing",fund:"€25.5M",fn:28,val:"Undisclosed",founders:"Hollingsworth brothers",focus:"AI exec assistant",ethos:"AI inbox",hq:"London",kp:null,ms:"€1M→€17M ARR 7mo",jobs:null},
  {id:"mimica",name:"Mimica",s:"Mimica",cat:"enterprise",yr:2019,emp:"Growing",fund:"$26.2M",fn:26,val:"Undisclosed",founders:"Planche",focus:"Process intelligence",ethos:"Observe→automate",hq:"London",kp:"Planche (CEO)",ms:"Khosla · EF alum",jobs:"https://www.mimica.ai/careers"},
  {id:"phoebe",name:"Phoebe AI",s:"Phoebe",cat:"devtools",yr:2024,emp:"Early",fund:"$17M",fn:17,val:"Undisclosed",founders:"Henderson, Summerfield",focus:"Software failure detection",ethos:"AI reliability",hq:"London",kp:null,ms:"$17M from GV",jobs:null},
  {id:"metaview",name:"Metaview",s:"Metaview",cat:"enterprise",yr:2018,emp:"Growing",fund:"$50M",fn:50,val:"Undisclosed",founders:"Magos",focus:"AI hiring",ethos:"Better hiring",hq:"London",kp:"Magos (CEO)",ms:"$35M B GV",jobs:"https://www.metaview.ai/careers"},
  {id:"unitary",name:"Unitary AI",s:"Unitary",cat:"safety",yr:2019,emp:"Small",fund:"Undisclosed",fn:5,val:"Undisclosed",founders:"Bateman",focus:"Content moderation",ethos:"Safer internet",hq:"London",kp:null,ms:"Most disruptive '24",jobs:null},
  {id:"paid-ai",name:"Paid AI",s:"Paid AI",cat:"devtools",yr:2024,emp:"Early",fund:"$21.6M",fn:22,val:"Undisclosed",founders:null,focus:"Billing for AI agents",ethos:"AI payment rails",hq:"London",kp:null,ms:"$21.6M Lightspeed",jobs:null},
  {id:"maze-ai",name:"Maze Security",s:"Maze",cat:"defence",yr:2024,emp:"Early",fund:"$31M",fn:31,val:"Undisclosed",founders:null,focus:"AI cloud security",ethos:"Auto cloud defence",hq:"London",kp:null,ms:"$25M A '25",jobs:null},
  {id:"oxbotica",name:"Oxbotica",s:"Oxbotica",cat:"autonomous",yr:2014,emp:"200+",fund:"~$225M",fn:225,val:"$1B+",founders:"Newman, Posner (Oxford)",focus:"Universal AV software",ethos:"Autonomy everywhere",hq:"Oxford+LDN",kp:"Newman (CEO)",ms:"$140M B (Google)",jobs:"https://www.oxbotica.com/careers/"},
  {id:"mind-foundry",name:"Mind Foundry",s:"Mind Foundry",cat:"enterprise",yr:2016,emp:"50-100",fund:"~$30M",fn:30,val:"Undisclosed",founders:"Roberts, Osborne (Oxford)",focus:"Human-centric AI",ethos:"Trustable AI",hq:"Oxford+LDN",kp:null,ms:"MoD contracts",jobs:"https://www.mindfoundry.ai/careers"},
  {id:"healx",name:"Healx",s:"Healx",cat:"biotech",yr:2014,emp:"50-100",fund:"~$68M",fn:68,val:"Undisclosed",founders:"Guilliams (Cambridge)",focus:"AI rare disease drugs",ethos:"Rare disease patients",hq:"Cambridge+LDN",kp:"Guilliams (CEO)",ms:"$56M B Atomico",jobs:"https://healx.io/careers/"},
  {id:"robin-ai",name:"Robin AI",s:"Robin AI",cat:"enterprise",yr:2019,emp:"100+",fund:"~$52M",fn:52,val:"Undisclosed",founders:"Robinson",focus:"AI contract review",ethos:"AI legal",hq:"London",kp:"Robinson (CEO)",ms:"600+ clients",jobs:"https://www.robinai.com/careers"},
  {id:"v7",name:"V7 Labs",s:"V7",cat:"devtools",yr:2018,emp:"80+",fund:"~$33M",fn:33,val:"Undisclosed",founders:"Rizzoli, Edwardsson",focus:"AI data platform",ethos:"Better data→better AI",hq:"London",kp:"Rizzoli (CEO)",ms:"Samsung/Genentech · Air Street",jobs:"https://www.v7labs.com/careers"},
  {id:"diffblue",name:"Diffblue",s:"Diffblue",cat:"devtools",yr:2016,emp:"50-100",fund:"~$40M",fn:40,val:"Undisclosed",founders:"Kroening (Oxford CS)",focus:"AI code testing",ethos:"AI writes tests",hq:"Oxford+LDN",kp:null,ms:"Goldman backed",jobs:"https://www.diffblue.com/careers/"},
  {id:"builderai",name:"Builder.ai",s:"Builder.ai",cat:"enterprise",yr:2016,emp:"700+",fund:"~$450M",fn:450,val:"$1B+",founders:"Duggal",focus:"AI no-code",ethos:"Software for everyone",hq:"London",kp:"Duggal (CEO)",ms:"MS+QIA backed",jobs:null},
  {id:"basecamp-res",name:"Basecamp Research",s:"Basecamp",cat:"biotech",yr:2020,emp:"50+",fund:"~$80M",fn:80,val:"Undisclosed",founders:"Mayall",focus:"Biodiversity DNA→protein AI",ethos:"Nature-first",hq:"London",kp:"Mayall (CEO)",ms:"$60M B Nvidia",jobs:null},
  {id:"papercup",name:"Papercup",s:"Papercup",cat:"generative",yr:2017,emp:"50+",fund:"~$20M",fn:20,val:"Undisclosed",founders:"Sherwood, Gao",focus:"AI video dubbing",ethos:"Every voice, every lang",hq:"London",kp:null,ms:"Sky/Bloomberg clients",jobs:null},
  {id:"mozart-ai",name:"Mozart AI",s:"Mozart AI",cat:"generative",yr:2025,emp:"Growing",fund:"$7.1M",fn:7,val:"Undisclosed",founders:"Sundar Arvind, Arjun Khanna & Pascual Merita Torres",focus:"AI Generative Audio Workstation · music creation · prompt-driven workflows · stems, MIDI, synths, video · built on ElevenLabs models",ethos:"Amplify creativity, not replace it",hq:"London",kp:"Sundar Arvind (CEO), Arjun Khanna (CPO), Pascual Merita Torres (CTO)",ms:"$6M Seed (Feb 2026, Balderton) · 100K+ users in 2 months · 1M songs · 10M+ Spotify streams · Mobile app",jobs:"https://www.mozartai.com/"},
  {id:"veed",name:"VEED.io",s:"VEED",cat:"generative",yr:2018,emp:"200+",fund:"$40.7M",fn:41,val:"$140-210M",founders:"Sabba Keynejad & Tim Sherwood",focus:"AI-powered online video creation & editing · subtitles, AI avatars, background removal, live streaming · browser-based",ethos:"Make video creation accessible",hq:"London (Shoreditch)",kp:"Sabba Keynejad (CEO)",ms:"$35M A (Sequoia, 2022) · Millions of users · 50+ AI Avatars · #46 a16z Top 50 GenAI Web Products (Jan 2026)",jobs:"https://www.veed.io/careers"},
  // INVESTORS
  {id:"balderton",name:"Balderton Capital",s:"Balderton",cat:"investor",yr:2000,focus:"$3B+ AUM · Europe's most active Series A investor · Wayve, Cleo, Convergence, Revolut, Darktrace",hq:"King's Cross, London",kp:"Bernard Liautaud (Managing Partner, founder Business Objects) · Suranga Chandratillake (GP, founder Blinkx) · Rob Moffat (GP) · Daniel Waterhouse (GP) · James Wise (GP, Chair Sovereign AI) · Rana Yared (GP, ex-Goldman) · Tim Bunting (GP)",fn:0,jobs:"https://www.balderton.com/careers/"},
  {id:"atomico",name:"Atomico",s:"Atomico",cat:"investor",yr:2006,focus:"$5B+ AUM · Founded by Niklas Zennström (Skype) · Graphcore, Synthesia, PhysicsX, Healx",hq:"London",kp:"Niklas Zennström (Founder & CEO) · Siraj Khaliq (GP, AI lead) · Hiro Tamura (GP) · Carolina Brochado (GP) · Ben Blume (GP) · Lina Wenner (Partner)",fn:0,jobs:"https://www.atomico.com/careers/"},
  {id:"localglobe",name:"LocalGlobe",s:"LocalGlobe",cat:"investor",yr:2015,focus:"Seed · Synthesia, Cleo, Faculty, Tessian",hq:"London",kp:"Robin Klein (Co-Founder) · Saul Klein (Co-Founder) · Remus Brett (GP) · Mish Mashkautsan (GP) · Julia Hawkins (GP)",fn:0,jobs:null},
  {id:"air-street",name:"Air Street Capital",s:"Air Street",cat:"investor",yr:2019,focus:"Specialist AI fund · State of AI Report · Wayve, Faculty, LabGenius",hq:"London",kp:"Nathan Benaich (Founder & GP)",fn:0,jobs:null},
  {id:"sequoia-eu",name:"Sequoia Capital",s:"Sequoia",cat:"investor",yr:1972,focus:"ElevenLabs $500M Series D · $85B+ AUM globally",hq:"LDN / SF",kp:"Luciana Lixandru (Partner, Europe) · Matt Miller (Partner, Europe) · Doug Leone (Managing Member, legacy) · Roelof Botha (Managing Partner)",fn:0,jobs:"https://www.sequoiacap.com/careers/"},
  {id:"accel",name:"Accel",s:"Accel",cat:"investor",yr:1983,focus:"$50B+ AUM · Synthesia, Helsing, Darktrace, UiPath, CrowdStrike",hq:"London",kp:"Luciana Lixandru (Partner) · Philippe Botteri (Partner, Europe) · Harry Sheridan (Partner) · Seth Pierrepont (Partner, London)",fn:0,jobs:"https://www.accel.com/careers/"},
  {id:"softbank",name:"SoftBank Vision Fund",s:"SoftBank",cat:"investor",yr:2017,focus:"$100B+ Vision Fund · Wayve $1.05B, Tractable, Graphcore",hq:"London",kp:"Masayoshi Son (Founder & Chairman) · Rajeev Misra (former CEO) · Munish Varma (Managing Partner) · Yanni Pipilis (Managing Partner, Europe)",fn:0,jobs:null},
  {id:"nvidia-inv",name:"Nvidia (Strategic)",s:"Nvidia",cat:"investor",yr:1993,focus:"£2B UK commitment · Wayve, Synthesia, ElevenLabs, PolyAI",hq:"US",kp:"Jensen Huang (CEO) · Mohamed 'Sid' Siddeek (VP Strategic Investments)",fn:0,jobs:null},
  {id:"gv",name:"GV",s:"GV",cat:"investor",yr:2009,focus:"$10B+ AUM · Synthesia Series E, Isomorphic, Phoebe AI",hq:"London",kp:"Tom Hulme (GP, London, founder IDEO/OpenIDEO) · Krishna Sherma (GP) · Tyson Clark (GP, AI/ML)",fn:0,jobs:null},
  {id:"khosla",name:"Khosla Ventures",s:"Khosla",cat:"investor",yr:2004,focus:"PolyAI, Mimica, ElevenLabs",hq:"US",kp:"Vinod Khosla (Founder, co-founder Sun Microsystems) · Samir Kaul (Managing Partner) · Sven Strohband (Managing Director)",fn:0,jobs:null},
  {id:"index",name:"Index Ventures",s:"Index",cat:"investor",yr:1996,focus:"$5B+ AUM · Tessl, Figma, Notion, Roblox",hq:"LDN / SF",kp:"Neil Rimer (Co-Founder) · Danny Rimer (Partner) · Mark Goldberg (Partner) · Martin Mignot (Partner, London)",fn:0,jobs:"https://www.indexventures.com/careers/"},
  {id:"lightspeed",name:"Lightspeed",s:"Lightspeed",cat:"investor",yr:2000,focus:"$18B+ AUM · Helsing, Paid AI",hq:"London",kp:"Arslan Ashraf (Partner, Europe) · Anoushka Vaswani (Partner, London) · Gustav Söderström (Partner)",fn:0,jobs:null},
  {id:"plural",name:"Plural",s:"Plural",cat:"investor",yr:2022,focus:"€400M Fund II · Helsing, Unitary, Metaview, Robin AI",hq:"London",kp:"Taavet Hinrikus (Co-Founder, founder Wise) · Ian Hogarth (Co-Founder, Chair AISI) · Cillian Kieran (Partner)",fn:0,jobs:null},
  {id:"mmc",name:"MMC Ventures",s:"MMC",cat:"investor",yr:2000,focus:"UK's most active AI investor · 144 companies, 4 unicorns (Synthesia, MUBI, Copper, Gousto) · ~$1B AUM · Seed & Series A · research-led",ethos:"Backing transformative tech",hq:"London",kp:"Bruce Macfarlane (Founding Partner), Simon Menashy (Managing Partner), David Kelnar (Partner, Research)",ms:"144 companies · 4 unicorns · £358M invested since 2010 · £501M portfolio value (Mar 2025) · State of AI reports",emp:"31",fn:0,jobs:null},
  // ACADEMIC
  {id:"ucl",name:"UCL",s:"UCL",cat:"academic",yr:1826,focus:"Gatsby Unit · DM birthplace · 46 spinouts £3.4B",hq:"King's Cross",fn:0,jobs:null},
  {id:"cambridge",name:"Cambridge",s:"Cambridge",cat:"academic",yr:1209,focus:"ML Group · #1 GenAI founders EU",hq:"Cambridge",fn:0,jobs:null},
  {id:"oxford",name:"Oxford",s:"Oxford",cat:"academic",yr:1096,focus:"OATML · NLP · Onfido/Exscientia/Oxbotica spinouts",hq:"Oxford",fn:0,jobs:null},
  {id:"imperial",name:"Imperial",s:"Imperial",cat:"academic",yr:1907,focus:"Robotics · CV · 7% EU GenAI founders",hq:"S. Kensington",fn:0,jobs:null},
  {id:"turing",name:"Turing Institute",s:"Turing",cat:"academic",yr:2015,focus:"National AI institute · 13+ unis",hq:"King's Cross",fn:0,jobs:null},
  // ACCELERATORS
  {id:"ef",name:"Entrepreneur First",s:"EF",cat:"investor",yr:2011,focus:"$10B+ portfolio. Tractable/Cleo/PolyAI",hq:"London",fn:0,jobs:null},
  {id:"seedcamp",name:"Seedcamp",s:"Seedcamp",cat:"investor",yr:2007,focus:"550+ cos · 10+ unicorns",hq:"London",fn:0,jobs:null},
];

// ── EDGES ───────────────────────────────────────────────────────────────
export const edges=[
  {s:"deepmind",t:"ineffable",ty:"alumni",l:"David Silver"},
  {s:"deepmind",t:"isomorphic",ty:"spinoff",l:"Hassabis dual CEO"},
  {s:"deepmind",t:"mistral",ty:"alumni",l:"Mensch"},
  {s:"deepmind",t:"elevenlabs",ty:"alumni",l:"Dąbkowski"},
  {s:"deepmind",t:"ms-research",ty:"alumni",l:"Suleyman→MS AI"},
  {s:"deepmind",t:"meta-ai",ty:"alumni",l:"Fergus→FAIR"},
  {s:"deepmind",t:"latent-labs",ty:"alumni",l:"Kohl"},
  {s:"deepmind",t:"convergence",ty:"alumni",l:"DM team"},
  {s:"ucl",t:"deepmind",ty:"academic",l:"Gatsby"},
  {s:"ucl",t:"synthesia",ty:"academic",l:"Agapito"},
  {s:"ucl",t:"holistic-ai",ty:"academic",l:"Founders"},
  {s:"cambridge",t:"wayve",ty:"academic",l:"Kendall PhD"},
  {s:"cambridge",t:"polyai",ty:"academic",l:"All 3 founders"},
  {s:"cambridge",t:"darktrace",ty:"academic"},
  {s:"cambridge",t:"tractable",ty:"academic",l:"Ranca"},
  {s:"cambridge",t:"healx",ty:"academic",l:"Guilliams"},
  {s:"oxford",t:"cohere",ty:"academic",l:"Gomez"},
  {s:"oxford",t:"onfido",ty:"academic",l:"3 students"},
  {s:"oxford",t:"exscientia",ty:"academic"},
  {s:"oxford",t:"oxbotica",ty:"academic",l:"Newman/Posner"},
  {s:"oxford",t:"mind-foundry",ty:"academic",l:"Roberts/Osborne"},
  {s:"oxford",t:"diffblue",ty:"academic",l:"Kroening"},
  {s:"imperial",t:"elevenlabs",ty:"academic",l:"Staniszewski"},
  {s:"imperial",t:"tractable",ty:"academic",l:"Dalyac"},
  {s:"softbank",t:"wayve",ty:"investment",l:"$1.05B C"},
  {s:"softbank",t:"tractable",ty:"investment"},
  {s:"softbank",t:"graphcore",ty:"investment",l:"Acquired"},
  {s:"softbank",t:"exscientia",ty:"investment"},
  {s:"sequoia-eu",t:"elevenlabs",ty:"investment",l:"$500M D"},
  {s:"sequoia-eu",t:"ineffable",ty:"investment",l:"In talks"},
  {s:"nvidia-inv",t:"wayve",ty:"investment"},
  {s:"nvidia-inv",t:"synthesia",ty:"investment"},
  {s:"nvidia-inv",t:"elevenlabs",ty:"investment"},
  {s:"nvidia-inv",t:"polyai",ty:"investment"},
  {s:"nvidia-inv",t:"latent-labs",ty:"investment"},
  {s:"nvidia-inv",t:"basecamp-res",ty:"investment"},
  {s:"gv",t:"synthesia",ty:"investment",l:"$200M E"},
  {s:"gv",t:"isomorphic",ty:"investment"},
  {s:"gv",t:"phoebe",ty:"investment"},
  {s:"gv",t:"metaview",ty:"investment"},
  {s:"balderton",t:"wayve",ty:"investment"},
  {s:"balderton",t:"cleo",ty:"investment"},
  {s:"balderton",t:"convergence",ty:"investment"},
  {s:"atomico",t:"graphcore",ty:"investment"},
  {s:"atomico",t:"synthesia",ty:"investment"},
  {s:"atomico",t:"physicsx",ty:"investment",l:"$135M B"},
  {s:"atomico",t:"healx",ty:"investment",l:"$56M B"},
  {s:"localglobe",t:"synthesia",ty:"investment"},
  {s:"localglobe",t:"cleo",ty:"investment"},
  {s:"localglobe",t:"faculty",ty:"investment"},
  {s:"localglobe",t:"papercup",ty:"investment"},
  {s:"air-street",t:"wayve",ty:"investment"},
  {s:"air-street",t:"synthesia",ty:"investment"},
  {s:"air-street",t:"elevenlabs",ty:"investment"},
  {s:"air-street",t:"tractable",ty:"investment"},
  {s:"air-street",t:"v7",ty:"investment"},
  {s:"accel",t:"synthesia",ty:"investment"},
  {s:"accel",t:"helsing",ty:"investment"},
  {s:"index",t:"tessl",ty:"investment"},
  {s:"lightspeed",t:"helsing",ty:"investment"},
  {s:"lightspeed",t:"paid-ai",ty:"investment"},
  {s:"khosla",t:"polyai",ty:"investment"},
  {s:"khosla",t:"mimica",ty:"investment"},
  {s:"khosla",t:"elevenlabs",ty:"investment"},
  {s:"plural",t:"helsing",ty:"investment"},
  {s:"plural",t:"unitary",ty:"investment"},
  {s:"plural",t:"metaview",ty:"investment"},
  {s:"plural",t:"robin-ai",ty:"investment"},
  {s:"ef",t:"tractable",ty:"accelerator"},
  {s:"ef",t:"cleo",ty:"accelerator"},
  {s:"ef",t:"polyai",ty:"accelerator"},
  {s:"ef",t:"mimica",ty:"accelerator"},
  {s:"seedcamp",t:"metaview",ty:"accelerator"},
  {s:"faculty",t:"openai",ty:"partnership",l:"Red teaming"},
  {s:"turing",t:"ucl",ty:"academic"},
  {s:"turing",t:"cambridge",ty:"academic"},
  {s:"turing",t:"oxford",ty:"academic"},
  {s:"meta-ai",t:"cohere",ty:"alumni",l:"Pineau"},
  {s:"cohere",t:"convergence",ty:"alumni"},
  {s:"graphcore",t:"deepmind",ty:"partnership",l:"Hassabis angel"},
  {s:"oxbotica",t:"wayve",ty:"partnership"},
  {s:"gv",t:"solveai",ty:"investment",l:"Led $45M A"},
  {s:"accel",t:"solveai",ty:"investment",l:"Led $5M pre-seed"},
  {s:"deepmind",t:"finster",ty:"alumni",l:"Jayakumar 7yr"},
  {s:"plural",t:"callosum",ty:"investment",l:"Led $10.25M Seed"},
  {s:"balderton",t:"mozart-ai",ty:"investment",l:"Led $6M Seed"},
  {s:"sequoia-eu",t:"veed",ty:"investment",l:"Led $35M Series A"},
  {s:"nvidia-inv",t:"nscale",ty:"investment",l:"$2B C investor"},
  {s:"thrive",t:"isomorphic",ty:"investment",l:"Led $600M A"},
  {s:"battery",t:"signal-ai",ty:"investment",l:"Led $165M"},
  {s:"georgian",t:"polyai",ty:"investment",l:"Led $86M D"},
  {s:"balderton",t:"sovereign-ai",ty:"partnership",l:"James Wise chairs"},
  {s:"localglobe",t:"olix",ty:"investment",l:"$220M A"},
  {s:"ef",t:"olix",ty:"investment",l:"$220M A"},
  {s:"plural",t:"olix",ty:"investment",l:"$220M A"},
  // Enrichment sweep — Mar 2026
  {s:"lightspeed",t:"anthropic",ty:"investment",l:"Led $3.5B E"},
  {s:"sequoia-eu",t:"anthropic",ty:"investment",l:"$2B F"},
  {s:"nvidia-inv",t:"anthropic",ty:"investment",l:"$10B strategic"},
  {s:"nvidia-inv",t:"cohere",ty:"investment",l:"Series C+D"},
  {s:"index",t:"cohere",ty:"investment",l:"Led Series A"},
  {s:"lightspeed",t:"helsing",ty:"investment",l:"Series C+D"},
  {s:"accel",t:"helsing",ty:"investment",l:"Series C+D"},
  {s:"lightspeed",t:"mistral",ty:"investment",l:"Series B co-lead"},
  {s:"gv",t:"oxbotica",ty:"investment",l:"$140M B"},
  {s:"nvidia-inv",t:"encord",ty:"investment",l:"€50M C investor"},
  {s:"lightspeed",t:"stability",ty:"investment",l:"$100M Seed"},
  {s:"ef",t:"faculty",ty:"investment",l:"EF alum"},
  {s:"ef",t:"mimica",ty:"investment",l:"EF alum"},
  {s:"ef",t:"tractable",ty:"investment",l:"EF alum"},
  {s:"seedcamp",t:"faculty",ty:"investment",l:"Seed"},
  {s:"seedcamp",t:"cleo",ty:"investment",l:"Seed"},
  {s:"seedcamp",t:"synthesia",ty:"investment",l:"Seed"},
  {s:"mmc",t:"faculty",ty:"investment",l:"Series A"},
  {s:"mmc",t:"healx",ty:"investment",l:"Seed"},
  {s:"mmc",t:"signal-ai",ty:"investment",l:"$165M Growth"},
  {s:"mmc",t:"synthesia",ty:"investment",l:"Early investor"},
  {s:"mmc",t:"physicsx",ty:"investment",l:"$135M B"},
  {s:"mmc",t:"encord",ty:"investment",l:"Investor"},
  {s:"mmc",t:"holistic-ai",ty:"investment",l:"Investor"},
  {s:"mmc",t:"albatross-ai",ty:"investment",l:"Led $12.5M Seed"},
  {s:"mmc",t:"peak-ai",ty:"investment",l:"Early (exited UiPath)"},
  {s:"mmc",t:"condukt",ty:"investment",l:"Seed"},
  {s:"mmc",t:"blackwall",ty:"investment",l:"Investor"},
  {s:"mmc",t:"nexcade",ty:"investment",l:"Pre-Seed"},
  {s:"lightspeed",t:"condukt",ty:"investment",l:"Investor"},
  {s:"air-street",t:"benevolentai",ty:"investment",l:"Early investor"},
  {s:"cambridge",t:"callosum",ty:"academic",l:"Both founders PhD"},
];
